SELECT ASM.EMPLOYEE_NUMBER, 
       ASM.EMPLOYEE_FULL_NAME,
       PEA.SEGMENT3                 AS  BANK_ACCOUNT,
       SUM(ARD.SAVING_RETIREMENT)   AS  SAVING_RETIREMENT
  FROM ATET_RETIREMENT_DISPERSION_TB    ARD,
       ATET_SAVINGS_BANK                ASB,
       ATET_SB_MEMBERS                  ASM,
       PER_ASSIGNMENTS_F                PAF,
       PAY_PERSONAL_PAYMENT_METHODS_F   PPPM,
       PAY_EXTERNAL_ACCOUNTS            PEA
 WHERE 1 = 1
   AND ARD.SAVING_BANK_ID = ASB.SAVING_BANK_ID
   AND ASB.YEAR = :P_YEAR
   AND ARD.PAYMENT_METHOD_ID  = :P_PAYMENT_METHOD_ID
   AND ARD.MEMBER_ID = ASM.MEMBER_ID
   AND PAF.PERSON_ID = ASM.PERSON_ID
   AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
   AND PPPM.ASSIGNMENT_ID = PAF.ASSIGNMENT_ID
   AND PPPM.ORG_PAYMENT_METHOD_ID = :P_PAYMENT_METHOD_ID
   AND SYSDATE BETWEEN PPPM.EFFECTIVE_START_DATE AND PPPM.EFFECTIVE_END_DATE
   AND PPPM.EXTERNAL_ACCOUNT_ID = PEA.EXTERNAL_ACCOUNT_ID
 GROUP BY ASM.EMPLOYEE_NUMBER,
          ASM.EMPLOYEE_FULL_NAME,
          PEA.SEGMENT3
 ORDER BY ASM.EMPLOYEE_NUMBER;