SELECT DISTINCT
       FAV.ASSET_NUMBER             AS  ASSET_NUMBER,
       FAV.DESCRIPTION              AS  ASSET_DESCRIPTION,
       FAV.TAG_NUMBER               AS  ASSET_TAG,
       FAV.SERIAL_NUMBER            AS  ASSET_SERIAL_NUMBER,
       FAV.CURRENT_UNITS            AS  ASSET_CURRENT_UNITS,
       FAV.ATTRIBUTE_CATEGORY_CODE  AS  ASSET_CATEGORY,
       FA.ORIGINAL_COST             AS  COST,       
       FA.BOOK_TYPE_CODE            AS  BOOK_TYPE_CODE,
       FBB.DATE_PLACED_IN_SERVICE   AS  ASSET_DATE_IN_SERVICE,
       FA.DEPRN_METHOD_CODE         AS  METHOD_CODE,
       FA.PRORATE_CONVENTION_CODE   AS  PRORATE_CODE,
       GCC.SEGMENT1 ||
       GCC.SEGMENT2 ||
       GCC.SEGMENT3 ||
       GCC.SEGMENT4 ||
       GCC.SEGMENT5 ||
       GCC.SEGMENT6                 AS  CODE_COMBINTION,
       FL.SEGMENT1 || '.' ||
       FL.SEGMENT2 || '.' ||
       FL.SEGMENT3                  AS  LOCATION
  FROM FA_ADDITIONS_V           FAV,
       FA_BOOKS                 FA,
       FA_BOOKS_BOOK_CONTROLS_V FBB,
       FA_DISTRIBUTION_HISTORY  FDH,
       GL_CODE_COMBINATIONS     GCC,
       FA_LOCATIONS             FL
 WHERE 1 = 1 
   AND FAV.ASSET_ID = FA.ASSET_ID
   AND FA.BOOK_TYPE_CODE = 'CORP GRB'
   AND NVL(FA.DISABLED_FLAG, 'N') = 'N'
   AND FA.TRANSACTION_HEADER_ID_OUT IS NULL
   AND FAV.ASSET_ID = FBB.ASSET_ID
   AND FA.BOOK_TYPE_CODE = FDH.BOOK_TYPE_CODE
   AND FAV.ASSET_ID = FDH.ASSET_ID
   AND FDH.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
   AND FDH.LOCATION_ID = FL.LOCATION_ID
 ORDER BY FAV.ASSET_NUMBER
   
   
    
    