--SELECT SUM(IMPORTE) FROM(

    SELECT DISTINCT
           POPM.PMETH_INFORMATION1          AS  ID_EMPRESA,
           TO_NUMBER(PAPF.EMPLOYEE_NUMBER)  AS  NUM_EMPLEADO,
           PPP.VALUE                        AS  IMPORTE,
           FLV.MEANING                      AS  BANCO
      FROM PAY_PAYROLLS_F               PPF,
           PAY_PAYROLL_ACTIONS          PPA,
           PER_ALL_ASSIGNMENTS_F        PAAF,
           PAY_ASSIGNMENT_ACTIONS       PAA,
           PAY_PRE_PAYMENTS             PPP,
           PAY_ORG_PAYMENT_METHODS_F    POPM,
           PER_ALL_PEOPLE_F             PAPF,
           PAY_EXTERNAL_ACCOUNTS        PEA,
           FND_LOOKUP_VALUES            FLV
     WHERE PPF.PAYROLL_ID = NVL(:P_PAYROLL_ID, PPF.PAYROLL_ID)
       AND PPF.PAYROLL_ID = PPA.PAYROLL_ID
       AND PPA.ACTION_TYPE IN('P', 'U')
       AND PPA.CONSOLIDATION_SET_ID = NVL(:P_CONSOLIDATION_ID, PPA.CONSOLIDATION_SET_ID)
       AND PPA.START_DATE >= :var_start_date 
       AND PPA.EFFECTIVE_DATE <= :var_end_date
       AND APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(PPF.PAYROLL_NAME) = :P_PERIOD_TYPE
       AND PPF.PAYROLL_ID = PAAF.PAYROLL_ID
       AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
       AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
       AND PPA.EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
       AND PPP.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID
       AND PPP.ORG_PAYMENT_METHOD_ID = POPM.ORG_PAYMENT_METHOD_ID
       AND POPM.ORG_PAYMENT_METHOD_NAME LIKE'%EASYVALE%'
       AND SUBSTR(POPM.ORG_PAYMENT_METHOD_NAME, 1, 2) = SUBSTR(PPF.PAYROLL_NAME, 1, 2)
       AND POPM.PMETH_INFORMATION1 IS NOT NULL
       AND PAPF.PERSON_ID = PAAF.PERSON_ID
       AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND NVL(PAAF.EFFECTIVE_END_DATE, SYSDATE +1)
       AND PAAF.PRIMARY_FLAG = 'Y'
       AND PAAF.ASSIGNMENT_TYPE = 'E'
       AND PAPF.CURRENT_EMPLOYEE_FLAG = 'Y'
       AND POPM.EXTERNAL_ACCOUNT_ID = PEA.EXTERNAL_ACCOUNT_ID
       AND FLV.LOOKUP_TYPE = 'MX_BANK'
       AND FLV.LANGUAGE = USERENV('LANG')
       AND FLV.LOOKUP_CODE = PEA.SEGMENT1
     ORDER BY 2 ASC
    
--   )