-- ALTER SESSION SET NLS_LANGUAGE = 'LATIN AMERICAN SPANISH';
-- ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';
 
--select sum(importe)
--from (

SELECT DISTINCT
   PM.PMETH_INFORMATION1            AS  ID_EMPRESA,
   PPF.EMPLOYEE_NUMBER              AS  NUM_EMPLEADO,
   PPP.VALUE                        AS  IMPORTE,
   FLV.MEANING                      AS  BANCO,
   PPF.PERSON_ID,
   PP.PAYROLL_NAME,
   PA.CONSOLIDATION_SET_ID,
   PA.START_DATE,
   PA.EFFECTIVE_DATE
   
  FROM PAY_PAYROLLS_F              PP,  
       PAY_ORG_PAYMENT_METHODS_F   PM,
       PAY_PAYROLL_ACTIONS         PA,
       PER_ALL_ASSIGNMENTS_F       AA,
       PAY_ASSIGNMENT_ACTIONS_V    PAA,
       PAY_PRE_PAYMENTS            PPP,   
       PER_PEOPLE_F                PPF,      
       PAY_EXTERNAL_ACCOUNTS       PEA,
       FND_LOOKUP_VALUES           FLV
 WHERE 1 = 1
   AND SUBSTR(PM.ORG_PAYMENT_METHOD_NAME, 1, 2) = SUBSTR(PP.PAYROLL_NAME, 1, 2)
   AND APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(PP.PAYROLL_NAME) = :P_PERIOD_TYPE
   AND PA.PAYROLL_ID = PP.PAYROLL_ID
   AND AA.PAYROLL_ID = PP.PAYROLL_ID
   AND (PAA.ASSIGNMENT_ID = AA.ASSIGNMENT_ID AND PAA.PAYROLL_ACTION_ID = PA.PAYROLL_ACTION_ID)
   AND PPP.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID   
   AND PA.EFFECTIVE_DATE BETWEEN AA.EFFECTIVE_START_DATE AND AA.EFFECTIVE_END_DATE
   AND PA.EFFECTIVE_DATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
   AND PPF.PERSON_ID = AA.PERSON_ID      
   AND PEA.EXTERNAL_ACCOUNT_ID = PM.EXTERNAL_ACCOUNT_ID
   AND FLV.LOOKUP_CODE = PEA.SEGMENT1
   AND PP.PAYROLL_ID LIKE '%' || :P_PAYROLL_ID || '%' 
   AND PA.CONSOLIDATION_SET_ID = :P_CONSOLIDATION_ID
   AND PM.ORG_PAYMENT_METHOD_NAME = '02-EASYVALE DESPENSA'   
   AND PM.ORG_PAYMENT_METHOD_ID = PPP.ORG_PAYMENT_METHOD_ID
   AND PM.OBJECT_VERSION_NUMBER = (SELECT MAX(PM.OBJECT_VERSION_NUMBER)
                                     FROM PAY_ORG_PAYMENT_METHODS_F POPM
                                    WHERE POPM.ORG_PAYMENT_METHOD_NAME = '02-EASYVALE DESPENSA'
                                      AND PM.ORG_PAYMENT_METHOD_ID = PPP.ORG_PAYMENT_METHOD_ID)
   AND LOOKUP_TYPE = 'MX_BANK'
   AND LANGUAGE = USERENV('LANG')
   AND PA.ACTION_TYPE IN ('U', 'P')
   AND (PA.START_DATE >= :var_start_date AND PA.EFFECTIVE_DATE <= :var_end_date)
  ORDER BY PPF.EMPLOYEE_NUMBER
  
--  )
  
  