LOAD DATA
BADFILE '/PAC_UPDATE_DIRECT_DEPOSIT.BAD'
DISCARDFILE '/PAC_UPDATE_DIRECT_DEPOSIT.DSC'
REPLACE
INTO TABLE APPS.PAC_UPDATE_DIRECT_DEPOSIT_TB
Fields terminated by "," Optionally enclosed by '"'
(
  EMPLOYEE_NUMBER,
  ACCOUNT_NUMBER,
  CARD_NUMBER
)

