SELECT PPA.PAYROLL_ACTION_ID,
       PPA.ASSIGNMENT_SET_ID,
       PAA.ASSIGNMENT_ACTION_ID,
--       PCD.PERSON_ID,
       PTP.TIME_PERIOD_ID,
       PTP.END_DATE,
       PETF.ELEMENT_TYPE_ID,
       PAAF.ASSIGNMENT_NUMBER,
       PETF.ELEMENT_NAME,
       PRR.RUN_RESULT_ID,
--       PCD.DEBIT_AMOUNT,
--       PC.COST_ALLOCATION_KEYFLEX_ID,
--       PCD.CONCATENATED_SEGMENTS SEG,
--       PCD.SEGMENT1, 
--       PCD.SEGMENT2, 
--       PCD.SEGMENT3, 
--       PCD.SEGMENT4, 
--       PCD.SEGMENT5, 
--       PCD.SEGMENT6,
       HAOU.ATTRIBUTE7 CC, 
       HAOU.ATTRIBUTE3 MANO_DE_OBRA, 
       HAOU.ATTRIBUTE4 CARGA_SOCIAL,
       HAOU.ATTRIBUTE5 BONOS, 
       HAOU.ATTRIBUTE6 FONDO_DE_AHORRO,
       PETF.ATTRIBUTE1 CLASIFICACION_PAC 
  FROM PAY_PAYROLL_ACTIONS          PPA,
       PAY_PAYROLLS_F               PPF,
       PER_TIME_PERIODS             PTP,
       PAY_ASSIGNMENT_ACTIONS       PAA,
       PER_ALL_ASSIGNMENTS_F        PAAF,
       HR_ALL_ORGANIZATION_UNITS    HAOU,
       PAY_RUN_RESULTS              PRR,
       PAY_ELEMENT_TYPES_F          PETF
--       PAY_COSTS                    PC
 WHERE 1 = 1
   AND PPA.PAYROLL_ID = PPF.PAYROLL_ID
   AND PPF.PAYROLL_ID = :P_PAYROLL_ID
   AND PTP.TIME_PERIOD_ID = PPA.TIME_PERIOD_ID 
   AND PPA.EFFECTIVE_DATE BETWEEN NVL(:P_START_DATE, PTP.START_DATE) AND NVL(:P_END_DATE, PTP.END_DATE)
   AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
   AND PPF.PERIOD_TYPE = :P_PERIOD_TYPE
   AND NVL(PPA.ASSIGNMENT_SET_ID, 0) = NVL(:P_ASSIGNMENT_SET_ID, NVL(PPA.ASSIGNMENT_SET_ID, 0))
   AND PPA.CONSOLIDATION_SET_ID = NVL(:P_CONSOLIDATION_SET_ID, PPA.CONSOLIDATION_SET_ID)
   AND PAA.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
   AND PPA.EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND PAAF.ASS_ATTRIBUTE15 = 'PAC'
   AND PAAF.ORGANIZATION_ID = HAOU.ORGANIZATION_ID
   AND HAOU.ATTRIBUTE7 IS NOT NULL
   AND PPA.ACTION_TYPE IN ('Q', 'R')
   AND PAA.ACTION_STATUS = 'C'
   AND PRR.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID
   AND PRR.ELEMENT_TYPE_ID = PETF.ELEMENT_TYPE_ID
   AND PETF.ATTRIBUTE1 IS NOT NULL
   AND PETF.ATTRIBUTE1 <> 'N/A'
--   AND PC.RUN_RESULT_ID = PRR.RUN_RESULT_ID
   
 ORDER BY HAOU.ATTRIBUTE7,
          PAAF.ASSIGNMENT_NUMBER,
          PETF.ELEMENT_NAME;