SELECT COUNT(1) REGISTROS,
       'MIGRADOS' DESCRI
  FROM PAC_MASTEREDI_REPORT_TB
 WHERE 1 = 1
UNION
SELECT COUNT(1) REGISTROS,
       'PENDIENTES' DESCRI
  FROM PAC_MASTEREDI_REPORT_TB
 WHERE 1 = 1
   AND NOMREC IS NULL
UNION
SELECT COUNT(1) REGISTROS,
       'CON RETENCION' DESCRI
  FROM PAC_MASTEREDI_REPORT_TB
 WHERE 1 = 1
   AND TOTRET IS NOT NULL
UNION
SELECT COUNT(1) REGISTROS,
       'CON TRASLADO' DESCRI
  FROM PAC_MASTEREDI_REPORT_TB
 WHERE 1 = 1
   AND TOTTRA <> 0;
   
   
   
SELECT *
  FROM PAC_MASTEREDI_REPORT_TB
 WHERE 1 = 1
   AND TOTRET IS NOT NULL;   