ALTER SESSION SET CURRENT_SCHEMA=APPS;



SELECT *
  FROM AR_NOTES ARN
 WHERE 1 = 1
   AND ARN.CUSTOMER_TRX_ID = :P_CUSTOMER_TRX_ID
 ORDER 
    BY CREATION_DATE;
      

BEGIN
     DELETE AR_NOTES
      WHERE 1 = 1
        AND NOTE_ID = :P_NOTE_ID;
        
     COMMIT;  
END;   