SELECT PR.UNIDAD,
       MEAN.SERIAL_NUMBER,
       PR.TIPO,
       PR.RENDIMIENTO,       
       MEAN.ASSET_GROUP_DESCRIPTION
FROM PAC_RENDIMIENTOS               PR
LEFT JOIN     MTL_EAM_ASSET_NUMBERS_ALL_V    MEAN ON PR.UNIDAD = MEAN.DESCRIPTIVE_TEXT
