    SELECT SERIAL_NUMBER,
           INVENTORY_ITEM_ID,
           AREA,
           CATEGORY_NAME,
           EAM_ITEM_TYPE,
           PAC_FUEL_EFFICIENCY.FIND_METER_ID (SERIAL_NUMBER) METER_ID,
           PAC_FUEL_EFFICIENCY.GET_METER_READING(PAC_FUEL_EFFICIENCY.FIND_METER_ID (SERIAL_NUMBER)) METER_READING,
           CURRENT_ORGANIZATION_ID,
           LEVEL ,
           CONNECT_BY_ISLEAF 
           
      FROM MTL_EAM_ASSET_NUMBERS_ALL_V MOG
     WHERE ACTIVE_END_DATE IS NULL
       AND CURRENT_ORGANIZATION_ID = 102 
--       CONNECT_BY_ROOT serial_number = serial_number
--       AND CATEGORY_NAME LIKE '%LLANTA%' 
--       AND CATEGORY_NAME LIKE '%VEHICULO%'
       AND SERIAL_NUMBER NOT LIKE 'POS%'
--       AND ROWNUM <= 10
--       AND EAM_ITEM_TYPE = 1       
       AND AREA <> 'GRB'
--       AND AREA = 'REPARTO'
       AND PAC_FUEL_EFFICIENCY.FIND_METER_ID (SERIAL_NUMBER) = -1
     START WITH PARENT_GEN_OBJECT_ID IS NULL
   CONNECT BY NOCYCLE PRIOR GEN_OBJECT_ID = PARENT_GEN_OBJECT_ID;
   
   
   
   