SELECT FFV.FLEX_VALUE
  FROM FND_FLEX_VALUES      FFV,
       FND_FLEX_VALUE_SETS  FFVS
 WHERE 1 = 1
   AND FFV.FLEX_VALUE_SET_ID = FFVS.FLEX_VALUE_SET_ID
   AND FFVS.FLEX_VALUE_SET_NAME = 'PAC_FUEL_EC_FUEL_TYPES'