SELECT DISTINCT
       CII.INSTANCE_NUMBER      AS "VEHICLE_ID",
       CII.INSTANCE_DESCRIPTION AS VEHICLE,
       MC.SEGMENT1              AS CLASS,
       MC.SEGMENT2              AS VEHICLE_TYPE,
       CII.ATTRIBUTE10          AS FUEL_TYPE
  FROM CSI_ITEM_INSTANCES       CII,
       EAM_ORG_MAINT_DEFAULTS   EOMD,
       MTL_EAM_LOCATIONS        MEL,
       MTL_CATEGORIES_B         MC 
 WHERE 1 = 1
   AND CII.INSTANCE_ID  = EOMD.OBJECT_ID
   AND EOMD.AREA_ID = MEL.LOCATION_ID
   AND MEL.LOCATION_CODES <> 'GRB'
   AND CII.CATEGORY_ID = MC.CATEGORY_ID
   AND MC.SEGMENT1 = 'VEHICULO'
   AND MEL.LOCATION_CODES = :AREA
   AND CII.INSTANCE_NUMBER NOT LIKE 'PAC%'
   AND (MC.SEGMENT2 <> 'REMOLQUE'
    AND MC.SEGMENT2 <> 'SEMIREMOLQUE'
    AND MC.SEGMENT2 <> 'TOLVA'
    AND MC.SEGMENT2 <> 'DOLLY')
 ORDER BY VEHICLE_ID