SELECT HOU.ORGANIZATION_ID,
       HOU.NAME,
       HOI.ORG_INFORMATION_CONTEXT,
       HOI.ORG_INFORMATION3
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1
   AND HOU.ORGANIZATION_ID = HOI.ORGANIZATION_ID
   AND (   NAME LIKE 'UO CEDIS '||:P_NAME
        OR NAME LIKE 'CEDIS_' || REPLACE(:P_NAME, ' ', '_'))
   AND (   HOI.ORG_INFORMATION_CONTEXT = 'Operating Unit Information'
        OR HOI.ORG_INFORMATION_CONTEXT = 'Accounting Information');
        
        
        
SELECT HOU.ORGANIZATION_ID,
       HOU.NAME
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1      
   AND HOU.ORGANIZATION_ID = HOI.ORGANIZATION_ID
   AND HOU.NAME LIKE 'UO CEDIS '||:P_NAME
   AND HOI.ORG_INFORMATION_CONTEXT = 'Operating Unit Information';

   
   
   
SELECT HOU.ORGANIZATION_ID,
       HOU.NAME,
       HOI.ORG_INFORMATION3
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1      
   AND HOU.ORGANIZATION_ID = HOI.ORGANIZATION_ID
   AND NAME LIKE 'CEDIS_' || REPLACE(:P_NAME, ' ', '_')
   AND HOI.ORG_INFORMATION_CONTEXT = 'Accounting Information';
   
   
   
   
   
   
   
SELECT HOU.ORGANIZATION_ID,
       HOU.NAME,
       HOI.ORG_INFORMATION3
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1      
   AND HOU.ORGANIZATION_ID = HOI.ORGANIZATION_ID
   AND HOU.NAME LIKE 'UO CEDIS %'
   AND HOI.ORG_INFORMATION_CONTEXT = 'Operating Unit Information'
 ORDER BY HOU.ORGANIZATION_ID;
   
   
SELECT HOU.ORGANIZATION_ID,
       HOU.NAME
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1      
   AND HOU.ORGANIZATION_ID = HOI.ORGANIZATION_ID
   AND NAME LIKE 'CEDIS_' || REPLACE(:P_NAME, ' ', '_')
   AND HOI.ORG_INFORMATION_CONTEXT = 'Accounting Information'
   AND HOU.ORGANIZATION_ID > 300
 ORDER BY HOU.ORGANIZATION_ID;