SELECT COUNT(PUI.TABLE_NAME)
  FROM PO_UNIQUE_IDENTIFIER_CONT_ALL    PUI
 WHERE 1 = 1
   AND PUI.ORG_ID = :P_OPERATING_UNIT_ID
   AND (   PUI.TABLE_NAME = 'PO_HEADERS_QUOTE'
        OR PUI.TABLE_NAME = 'PO_HEADERS_RFQ'
        OR PUI.TABLE_NAME = 'PO_HEADERS'
        OR PUI.TABLE_NAME = 'PO_REQUISITION_HEADERS')