SELECT FUV1.USER_NAME                                       CREATED_BY,
       TO_CHAR(CREATION_DATE, 'DD-MON-YYYY HH24:MI:SS')     CREATION_DATE,
       FUV2.USER_NAME                                       LAST_UPDATED_BY,
       TO_CHAR(LAST_UPDATE_DATE, 'DD-MON-YYYY HH24:MI:SS')  LAST_UPDATE_DATE,
       REPLACE(COLUMN_DESC, '_', ' ')                       COLUMN_DESC,
       COLUMN_VAL,  
       PAC_VERIFY_CEDIS_PKG.VERIFY_STEP4(COLUMN_DESC, COLUMN_VAL, :P_ORG_INVENTORY_ID, :P_OPERATING_UNIT_ID)  VALIDATION
  FROM (SELECT TO_CHAR(MP.ORGANIZATION_CODE)                                             AS  "Organization_Code",
               TO_CHAR(HOU.NAME)                                                         AS  "Item_Master_Organization",
               TO_CHAR(MP.CALENDAR_CODE)                                                 AS  "Calendar",
               TO_CHAR(MP.STOCK_LOCATOR_CONTROL_CODE)                                    AS  "Locator_Control",
               TO_CHAR(MP.NEGATIVE_INV_RECEIPT_CODE)                                     AS  "Allow_Negative_Balances",
               TO_CHAR(MP.AUTO_DEL_ALLOC_FLAG)                                           AS  "Auto_Delete_Allocations",
               TO_CHAR(MP.PROCESS_ENABLED_FLAG)                                          AS  "Process_Manufacturing_Enabled",
               TO_CHAR(HOU1.NAME)                                                        AS  "Costing_Organization",
               TO_CHAR(ML.MEANING)                                                       AS  "Costing_Method",
               TO_CHAR(MP.GENERAL_LEDGER_UPDATE_CODE)                                    AS  "Transfer_to_GL",
               TO_CHAR(' ')                                                              AS  "Valuation_Accounts",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.MATERIAL_ACCOUNT))            AS  "Material",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.OUTSIDE_PROCESSING_ACCOUNT))  AS  "Outside_Processing",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.MATERIAL_OVERHEAD_ACCOUNT))   AS  "Material_Overhead",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.OVERHEAD_ACCOUNT))            AS  "Overhead",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.RESOURCE_ACCOUNT))            AS  "Resource",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.EXPENSE_ACCOUNT))             AS  "Expense",
               TO_CHAR(MP.LOT_NUMBER_GENERATION)                                         AS  "Lot_Control_Generation",
               TO_CHAR(MP.CHILD_LOT_NUMBER_LENGTH)                                       AS  "Child_Lot_Control_Total_Length",
               TO_CHAR(MP.SERIAL_NUMBER_GENERATION)                                      AS  "Serial_Control_Generation",
               TO_CHAR(MP.MATL_INTERORG_TRANSFER_CODE)                                   AS  "InterOrg_Transfer_Charge",
               TO_CHAR(' ')                                                              AS  "InterOrg_Transfer_Accounts",       
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INTERORG_TRANSFER_CR_ACCOUNT))AS  "Transfer_Credit",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INTERORG_PRICE_VAR_ACCOUNT))  AS  "Price_Variance",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INTERORG_RECEIVABLES_ACCOUNT))AS  "Receivable",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INTERORG_PAYABLES_ACCOUNT))   AS  "Payable",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INTRANSIT_INV_ACCOUNT))       AS  "Intransit_Inventory",
               TO_CHAR(' ')                                                              AS  "Receiving_Accounts",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.PURCHASE_PRICE_VAR_ACCOUNT))  AS  "Purchase_Price_Variance",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.INVOICE_PRICE_VAR_ACCOUNT))   AS  "Invoice_Price_Variance",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.AP_ACCRUAL_ACCOUNT))          AS  "Inventory_AP_Accrual",
               TO_CHAR( PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.ENCUMBRANCE_ACCOUNT))        AS  "Encumbrance",
               TO_CHAR(' ')                                                              AS  "Profit_and_Loss_Accounts",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.SALES_ACCOUNT))               AS  "Sales",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.COST_OF_SALES_ACCOUNT))       AS  "Cost_of_Goods_Sold",
               TO_CHAR(' ')                                                              AS  "Other_Accounts",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.DEFERRED_COGS_ACCOUNT))       AS  "Deferred_COGS_Account",
               TO_CHAR(PAC_VERIFY_CEDIS_PKG.GET_ACCOUNT(MP.AVERAGE_COST_VAR_ACCOUNT))    AS  "Cost_Variance_Account",
               TO_CHAR(MP.ATTRIBUTE_CATEGORY )                                           AS  "CONTEXT",
               TO_CHAR(MP.ATTRIBUTE10)                                                   AS  "TIPO_PROCESO",
               TO_CHAR(MP.ATTRIBUTE11)                                                   AS  "AREA",
               MP.CREATED_BY,
               MP.CREATION_DATE,
               MP.LAST_UPDATED_BY,
               MP.LAST_UPDATE_DATE
          FROM MTL_PARAMETERS           MP,
               HR_ORGANIZATION_UNITS    HOU,
               HR_ORGANIZATION_UNITS    HOU1,
               MFG_LOOKUPS              ML
         WHERE 1 = 1
           AND MP.ORGANIZATION_ID = :P_ORG_INVENTORY_ID
           AND HOU.ORGANIZATION_ID = MP.MASTER_ORGANIZATION_ID
           AND HOU1.ORGANIZATION_ID = MP.COST_ORGANIZATION_ID
           AND ML.LOOKUP_CODE = MP.PRIMARY_COST_METHOD
           AND ML.LOOKUP_TYPE = 'MTL_PRIMARY_COST'
        ) DETAIL
 UNPIVOT (COLUMN_VAL FOR COLUMN_DESC IN( "Organization_Code",
                                         "Item_Master_Organization",
                                         "Calendar",
                                         "Locator_Control",
                                         "Allow_Negative_Balances",
                                         "Auto_Delete_Allocations",
                                         "Process_Manufacturing_Enabled",
                                         "Costing_Organization",
                                         "Costing_Method",
                                         "Transfer_to_GL",
                                         "Valuation_Accounts",
                                         "Material",
                                         "Outside_Processing",
                                         "Material_Overhead",
                                         "Overhead",
                                         "Resource",
                                         "Expense",
                                         "Lot_Control_Generation",
                                         "Child_Lot_Control_Total_Length",
                                         "Serial_Control_Generation",
                                         "InterOrg_Transfer_Charge",
                                         "InterOrg_Transfer_Accounts",
                                         "Transfer_Credit",
                                         "Price_Variance",
                                         "Receivable",
                                         "Payable",
                                         "Intransit_Inventory",
                                         "Receiving_Accounts",
                                         "Purchase_Price_Variance",
                                         "Invoice_Price_Variance",
                                         "Inventory_AP_Accrual",
                                         "Encumbrance",
                                         "Profit_and_Loss_Accounts",
                                         "Sales",
                                         "Cost_of_Goods_Sold",
                                         "Other_Accounts",
                                         "Deferred_COGS_Account",
                                         "Cost_Variance_Account",
                                         "CONTEXT",
                                         "TIPO_PROCESO",
                                         "AREA")),
       FND_USER_VIEW  FUV1,
       FND_USER_VIEW  FUV2    
 WHERE 1 = 1
   AND FUV1.USER_ID = CREATED_BY
   AND FUV2.USER_ID = LAST_UPDATED_BY                                           
        