SELECT MP.ORGANIZATION_CODE                                                            AS   ORGANIZATION_CODE,
       FA.APPLICATION_NAME                                                             AS   APPLICATION_NAME,
       FR.RESPONSIBILITY_NAME                                                          AS   RESPONSABILITY_NAME,
       PAC_VERIFY_CEDIS_PKG.VERIFY_STEP5(MP.ORGANIZATION_CODE, FR.RESPONSIBILITY_NAME) AS   VALIDATION
  FROM ORG_ACCESS OA,
       MTL_PARAMETERS MP,
       HR_ORGANIZATION_UNITS HOU,
       FND_RESPONSIBILITY_VL FR,
       FND_APPLICATION_VL FA
 WHERE 1 = 1
   AND HOU.ORGANIZATION_ID = :P_ORG_INVENTORY_ID
   AND HOU.ORGANIZATION_ID = OA.ORGANIZATION_ID
   AND MP.ORGANIZATION_ID = HOU.ORGANIZATION_ID
   AND FR.RESPONSIBILITY_ID = OA.RESPONSIBILITY_ID
   AND FR.APPLICATION_ID = OA.RESP_APPLICATION_ID
   AND FA.APPLICATION_ID = OA.RESP_APPLICATION_ID
 