CREATE TABLE PAC_ASSET_ADDITIONS_TB
(
    DESCRIPTION           VARCHAR2(100),
    TAG_NUMBER            VARCHAR2(100),
    SERIAL_NUMBER         VARCHAR2(100),
    UNITS                 VARCHAR2(100),
    CATEGORY              VARCHAR2(100),
    COST                  VARCHAR2(100),
    VENDOR_NAME           VARCHAR2(240),
    INVOICE_NUMBER        VARCHAR2(100),
    BOOK_CODE             VARCHAR2(100),
    DATE_IN_SERVICE       VARCHAR2(100),
    DEPRECIATE_METHOD     VARCHAR2(100),
    PRORATE_CODE          VARCHAR2(100),
    CODE_COMBINATION      VARCHAR2(100),
    LOCATION              VARCHAR2(100)
)