BEGIN

    DELETE FROM XDO_TEMPLATES_B
    WHERE TEMPLATE_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_TEMPLATES_TL
    WHERE TEMPLATE_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_LOBS
    WHERE LOB_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_CONFIG_VALUES
    WHERE TEMPLATE_CODE = 'PAC_REPORTE_REND_SEMANAL';

    DELETE FROM XDO_DS_DEFINITIONS_B
    WHERE DATA_SOURCE_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_DS_DEFINITIONS_TL
    WHERE DATA_SOURCE_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_LOBS
    WHERE LOB_CODE = 'PAC_REPORTE_REND_SEMANAL';
     
    DELETE FROM XDO_CONFIG_VALUES
    WHERE DATA_SOURCE_CODE = 'PAC_REPORTE_REND_SEMANAL';
    
    COMMIT;

END;