SELECT
  RG.REQUEST_GROUP_NAME,
  RG.REQUEST_GROUP_CODE,
  RG.DESCRIPTION,
  CP.CONCURRENT_PROGRAM_NAME,
  CPT.USER_CONCURRENT_PROGRAM_NAME,
  DECODE(RGU.REQUEST_UNIT_TYPE,'P','Program','S','Set',RGU.REQUEST_UNIT_TYPE) "Unit Type"
FROM
  FND_REQUEST_GROUPS RG,
  FND_REQUEST_GROUP_UNITS RGU,
  FND_CONCURRENT_PROGRAMS CP,
  FND_CONCURRENT_PROGRAMS_TL CPT
WHERE RG.REQUEST_GROUP_ID = RGU.REQUEST_GROUP_ID
  AND RGU.REQUEST_UNIT_ID = CP.CONCURRENT_PROGRAM_ID
  AND CP.CONCURRENT_PROGRAM_ID = CPT.CONCURRENT_PROGRAM_ID
  AND CPT.USER_CONCURRENT_PROGRAM_NAME LIKE :P_CONC_PROG_NAME;