SELECT OOHA.ORDER_NUMBER,
       OOHA.ORDERED_DATE,
       HP.PARTY_NAME,
       OOHA.ORG_ID
  FROM OE_ORDER_HEADERS_ALL     OOHA,
       HZ_CUST_ACCOUNTS         HCA,
       HZ_PARTIES               HP
 WHERE 1 = 1
   AND OOHA.SOLD_TO_ORG_ID = HCA.CUST_ACCOUNT_ID
   AND HCA.PARTY_ID = HP.PARTY_ID
   AND OOHA.ORDER_CATEGORY_CODE = 'ORDER'
   AND OOHA.ORG_ID = 82
   AND OOHA.ORDER_NUMBER = :P_ORDER_NUMBER