PACKAGE PAC_VALIDATE_PKG IS
  
  
  FUNCTION	VALIDATE_TRAFFIC_NUMBER(P_TRAFFIC_NUMBER	NUMBER)
   					RETURN VARCHAR2;
  
  FUNCTION	IS_DEPARTURE_EXIST(P_TRAFFIC_NUMBER	NUMBER)
  					RETURN BOOLEAN;
  
  FUNCTION	IS_DEPARTURE_ARRIVAL_COMPLETE(P_TRAFFIC_NUMBER	NUMBER)
  					RETURN BOOLEAN;
  					
	FUNCTION IS_DEPARTURE_REGISTERED(P_TRAFFIC_NUMBER		NUMBER)
 						RETURN BOOLEAN;
 						
	FUNCTION IS_DEPARTURE_CLOSED(P_TRAFFIC_NUMBER		NUMBER)
 						RETURN BOOLEAN;
 						
	FUNCTION IS_ARRIVAL_CLOSED(P_TRAFFIC_NUMBER		NUMBER)
 					  RETURN BOOLEAN;
  
  FUNCTION IS_CANCELLED(p_traffic_number number) 
  					RETURN BOOLEAN;
  
END;