    SELECT DISTINCT
           CII.INSTANCE_NUMBER      AS VEHICLE_ID,
           CII.INSTANCE_DESCRIPTION AS VEHICLE,
           (CASE 
                WHEN MC.SEGMENT2 = 'TORTON'       THEN  'P/2.40'   
                WHEN MC.SEGMENT2 = 'TRACTOCAMION' THEN  'P/2.20'
            END)                    AS REN,
           PAC_FUEL_EC_REPORTS_PKG.GET_EFFICIENCY_ACUM(CII.INSTANCE_NUMBER, :CP_END_DATE) AS EFFICIENCY,
           PAC_FUEL_EC_REPORTS_PKG.GET_COMMENTS_LIST(CII.INSTANCE_NUMBER, :CP_END_DATE) AS COMMENTS,
           PAC_FUEL_EC_REPORTS_PKG.GET_LTS_DIFFERENCE_ACUM(CII.INSTANCE_NUMBER, :CP_END_DATE) AS LTS_DIFFERENCE
      FROM CSI_ITEM_INSTANCES       CII,
           EAM_ORG_MAINT_DEFAULTS   EOMD,
           MTL_EAM_LOCATIONS        MEL,
           MTL_CATEGORIES_B         MC 
     WHERE 1 = 1
       AND CII.INSTANCE_ID  = EOMD.OBJECT_ID
       AND EOMD.AREA_ID = MEL.LOCATION_ID
       AND CII.CATEGORY_ID = MC.CATEGORY_ID
       AND MC.SEGMENT1 = 'VEHICULO'
       AND MEL.LOCATION_CODES = 'REPARTO'
       AND CII.INSTANCE_NUMBER NOT LIKE 'PAC%'
       AND (MC.SEGMENT2 = 'TRACTOCAMION'
        OR MC.SEGMENT2 = 'TORTON')
     ORDER BY VEHICLE,
              VEHICLE_ID;