CREATE TABLE PAC_VISITS_CONTROL_TB (
    VISITOR_ID                          NUMBER          NOT NULL,
    VISITOR_DAY_ID                      NUMBER          NOT NULL,
    VISITOR_NAME                        VARCHAR2(100),
    VISITOR_COMPANY                     VARCHAR2(100),
    FLAG_IFE_CARD                       VARCHAR2(1),
    FLAG_DRIVER_LICENSE                 VARCHAR2(1),
    FLAG_PASSPORT                       VARCHAR2(1),
    FLAG_PROFESSIONAL_CERTIFICATE       VARCHAR2(1),
    FLAG_MILITARY_SERVICE_CARD          VARCHAR2(1),
    FLAG_OTHER_IDENTIFICATION           VARCHAR2(1),
    OTHER_IDENTIFICATION_NAME           VARCHAR2(50),
    REASON_VISIT                        VARCHAR2(100),
    ASSOCIATE_PERSON_ID                 NUMBER,
    ASSOCIATE_DEPARTMENT_ID             NUMBER,
    REGISTRATION_TIME_STAMP             DATE            NOT NULL,
    REGISTRATION_DATE                   DATE,
    REGISTRATION_TIME                   VARCHAR2(30),
    CHECK_IN                            VARCHAR2(30),
    CHECK_OUT                           VARCHAR2(30),
    VISITOR_LENGTH_STAY                 VARCHAR2(100),
    ATTRIBUTE1                          VARCHAR2(350),
    ATTRIBUTE2                          VARCHAR2(350),
    ATTRIBUTE3                          VARCHAR2(350),
    ATTRIBUTE4                          VARCHAR2(350),
    ATTRIBUTE5                          VARCHAR2(350),
    ATTRIBUTE6                          VARCHAR2(350),
    ATTRIBUTE7                          VARCHAR2(350),
    ATTRIBUTE8                          VARCHAR2(350),
    ATTRIBUTE9                          VARCHAR2(350),
    CREATED_BY                          NUMBER(15),
    CREATION_DATE                       DATE,
    LAST_UPDATED_BY                     NUMBER(15),
    LAST_UPDATE_DATE                    DATE,
    LAST_UPDATE_LOGIN                   NUMBER(15)
);
PAC_TIMECLOCK_CHECKS