PACKAGE PAC_VISITS_CONTROL_PKG IS
  
  PROCEDURE ON_WHEN_NEW_FORM_INSTANCE;
  
  PROCEDURE ON_WHEN_TIMER_EXPIRED;
  
  PROCEDURE CREATE_FOLIO;
  
  PROCEDURE ON_WHEN_RADIO_CHANGED;
  
  PROCEDURE ON_WHEN_NEW_RECORD_INSTANCE;
  
  PROCEDURE ON_INSERT;
  
  FUNCTION VALIDATE_DATA RETURN BOOLEAN;
  
  PROCEDURE ON_WHEN_TAB_PAGE_CHANGED;
  
  PROCEDURE ON_WHEN_BUTTON_PRESSED;
  
END;