PACKAGE BODY PAC_VISITS_CONTROL_PKG IS
  
  PROCEDURE ON_WHEN_NEW_FORM_INSTANCE IS
  	
  	TIME_TIMER		TIMER;
  	QUERY_TIMER		TIMER;
  	
  	BY_1_SEC		CONSTANT	NUMBER := 1000;
  	BY_60_SEC		CONSTANT	NUMBER := 60000;
  	
  BEGIN
  	
  	READ_IMAGE_FILE('$PER_TOP/forms/US/PAC_TIME_CLOCK.BMP','bmp','PAC_LOGO');
  	
  	TIME_TIMER := CREATE_TIMER('TIME_TIMER', 	 BY_1_SEC, 	REPEAT);
  	QUERY_TIMER := CREATE_TIMER('QUERY_TIMER', BY_60_SEC, REPEAT);
  	
  END ON_WHEN_NEW_FORM_INSTANCE;
  
  
  PROCEDURE ON_WHEN_TIMER_EXPIRED IS
  
  	TIMER_EXPIRED	VARCHAR(100) := get_application_property(TIMER_NAME);
  	var_date VARCHAR2(30) := TO_CHAR(SYSDATE + PAC_GET_TVALUE/1440,'dd/mm/yyyy'); --:SYSTEM.CURRENT_DATETIME; 
  	var_time VARCHAR2(30) := TO_CHAR(SYSDATE + PAC_GET_TVALUE/1440,'HH24:MI:SS'); --:SYSTEM.CURRENT_DATETIME; 
  
  BEGIN
  	
  	IF    TIMER_EXPIRED = 'TIME_TIMER' THEN
  		
  		:CONTROL.TXT_DATE := var_date;
  		:CONTROL.TXT_HOUR := SUBSTR(var_time, INSTR(var_time,' ') + 1);
  		
  	ELSIF TIMER_EXPIRED = 'QUERY_TIMER' THEN
  		NULL;
  	END IF;
  	
  END ON_WHEN_TIMER_EXPIRED;
  
  
  PROCEDURE CREATE_FOLIO IS
  BEGIN
  	
  	SELECT TO_CHAR(SYSDATE, 'YYMMDD') ||
		       TRIM(TO_CHAR((COUNT(PVC.VISITOR_DAY_ID) + 1), '000'))
		  INTO :PAC_VISITS_CONTROL_TB.VISITOR_DAY_ID
		  FROM PAC_VISITS_CONTROL_TB PVC
		 WHERE 1 = 1
		   AND PVC.VISITOR_DAY_ID LIKE (TO_CHAR(SYSDATE, 'YYMMDD') ||'%');
  	
  END CREATE_FOLIO;
  
  
  PROCEDURE ON_WHEN_RADIO_CHANGED IS
  BEGIN
  	
  	IF :PAC_VISITS_CONTROL_TB.IDENTIFICATION_TYPE = 'Otro' THEN
  		app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', ENABLED, PROPERTY_ON);
  		app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', REQUIRED, PROPERTY_ON);
  		:PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME := NULL;
  	ELSE
  		app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', ENABLED, PROPERTY_OFF);
  		app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', REQUIRED, PROPERTY_OFF);
  		:PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME := NULL;
  	END IF;
  	
  END ON_WHEN_RADIO_CHANGED;
  
  
  PROCEDURE ON_WHEN_NEW_RECORD_INSTANCE IS
  BEGIN
  	
  	app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', ENABLED, PROPERTY_OFF);
  	app_item_property.set_property('PAC_VISITS_CONTROL_TB.OTHER_IDENTIFICATION_NAME', REQUIRED, PROPERTY_OFF);
  	app_item_property.set_property('CONTROL.BTN_PRINT', ENABLED, PROPERTY_OFF);
  	
  END ON_WHEN_NEW_RECORD_INSTANCE;
  
  
  PROCEDURE ON_INSERT IS
  BEGIN
  	
  	null;
  	
  END ON_INSERT;
  
  
  PROCEDURE ON_PRE_INSERT IS
  BEGIN
  	FND_STANDARD.SET_WHO;
  END ON_PRE_INSERT;
  
  
END;