PACKAGE PAC_VISITS_CONTROL_PKG IS
  
  PROCEDURE ON_WHEN_NEW_FORM_INSTANCE;
  
  PROCEDURE ON_WHEN_TIMER_EXPIRED;
  
  PROCEDURE CREATE_FOLIO;
  
  PROCEDURE ON_WHEN_RADIO_CHANGED;
  
  PROCEDURE ON_WHEN_NEW_RECORD_INSTANCE;
  
  PROCEDURE ON_INSERT;
  
  PROCEDURE ON_PRE_INSERT;
  
END;