PACKAGE BODY PAC_VISITS_CONTROL_PKG IS
  
  PROCEDURE ON_WHEN_NEW_FORM_INSTANCE IS
  	TIME_TIMER	TIMER;
  	BY_1_SEC		CONSTANT	NUMBER := 1000;
  BEGIN
  	
  	READ_IMAGE_FILE('$PER_TOP/forms/US/PAC_TIME_CLOCK.BMP','bmp','PAC_LOGO');
  	
  	TIME_TIMER := CREATE_TIMER('TIME_TIMER', BY_1_SEC, REPEAT);
  	
 	END ON_WHEN_NEW_FORM_INSTANCE;
  
END;