PACKAGE BODY PAC_VISITS_VIEW_PKG IS
  

  PROCEDURE ON_PRE_QUERY IS
  BEGIN
  	
  	:CONTROL.TXT_TOTAL_VISITS := '0';
  	:CONTROL.TXT_ACTUAL_VISITS := '0';
  	
  END ON_PRE_QUERY;


	PROCEDURE ON_POST_QUERY IS
	BEGIN
		
		IF    :PAC_VISITS_VIEW_TB.CHECK_IN IS NULL AND :PAC_VISITS_VIEW_TB.CHECK_OUT IS NULL THEN
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_DAY_ID', 'BACKGROUND_WHITE');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_NAME', 'BACKGROUND_WHITE');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_COMPANY', 'BACKGROUND_WHITE');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_IN', 'BACKGROUND_WHITE');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_OUT', 'BACKGROUND_WHITE');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_LENGTH_STAY', 'BACKGROUND_WHITE');
		ELSIF :PAC_VISITS_VIEW_TB.CHECK_IN IS NOT NULL AND :PAC_VISITS_VIEW_TB.CHECK_OUT IS NOT NULL THEN
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_DAY_ID', 'BACKGROUND_GRAY');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_NAME', 'BACKGROUND_GRAY');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_COMPANY', 'BACKGROUND_GRAY');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_IN', 'BACKGROUND_GRAY');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_OUT', 'BACKGROUND_GRAY');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_LENGTH_STAY', 'BACKGROUND_GRAY');
		ELSIF :PAC_VISITS_VIEW_TB.CHECK_IN IS NOT NULL AND :PAC_VISITS_VIEW_TB.CHECK_OUT IS NULL THEN
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_DAY_ID', 'BACKGROUND_GREEN');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_NAME', 'BACKGROUND_GREEN');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_COMPANY', 'BACKGROUND_GREEN');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_IN', 'BACKGROUND_GREEN');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.CHECK_OUT', 'BACKGROUND_GREEN');
			SET_BACKGROUND('PAC_VISITS_VIEW_TB.VISITOR_LENGTH_STAY', 'BACKGROUND_GREEN');
		END IF;		
		
		FND_STANDARD.SET_WHO;
		
		SELECT COUNT(PVC.VISITOR_DAY_ID)
		  INTO :CONTROL.TXT_TOTAL_VISITS 
		  FROM PAC_VISITS_CONTROL_TB PVC
		 WHERE 1 = 1
		   AND VISITOR_DAY_ID LIKE (TO_CHAR(SYSDATE, 'YYMMDD') || '%');
		 
		SELECT COUNT(PVC.VISITOR_DAY_ID)
		  INTO :CONTROL.TXT_ACTUAL_VISITS 
		  FROM PAC_VISITS_CONTROL_TB PVC
		 WHERE 1 = 1
		   AND VISITOR_DAY_ID LIKE (TO_CHAR(SYSDATE, 'YYMMDD') || '%')
		   AND CHECK_IN IS NOT NULL
		   AND CHECK_OUT IS NULL;
		  
		
	END ON_POST_QUERY;
	
	
	PROCEDURE SET_BACKGROUND(ITEM VARCHAR2, BACKGROUND VARCHAR2) IS
	BEGIN
		app_item_property.set_property(ITEM, ENABLED, PROPERTY_TRUE);
		SET_ITEM_INSTANCE_PROPERTY(ITEM, CURRENT_RECORD, VISUAL_ATTRIBUTE, BACKGROUND);
		app_item_property.set_property(ITEM, ENABLED, PROPERTY_FALSE);
	END;
		
  
END;