CREATE OR REPLACE PROCEDURE APPS.RESET_SEQUENCE_PRC
IS
BEGIN
   
   --Borrado y Creación de la Secuencia PAC_ALTA_FONDO_AHORRO_EXE_SEQ.

   EXECUTE IMMEDIATE 'DROP SEQUENCE PAC_ALTA_FONDO_AHORRO_EXE_SEQ';

   EXECUTE IMMEDIATE
         'CREATE SEQUENCE PAC_ALTA_FONDO_AHORRO_EXE_SEQ '
      || 'START WITH 1 '
      || 'INCREMENT BY 1 '
      || 'NOCACHE '
      || 'NOCYCLE';


   --Borrado y Creación de la Secuencia PAC_FONDO_AHORRO_DAILY_SEQ

   EXECUTE IMMEDIATE 'DROP SEQUENCE PAC_FONDO_AHORRO_DAILY_SEQ';

   EXECUTE IMMEDIATE
         'CREATE SEQUENCE PAC_FONDO_AHORRO_DAILY_SEQ '
      || 'START WITH 1 '
      || 'INCREMENT BY 1 '
      || 'NOCACHE '
      || 'NOCYCLE';


   --Borrado y Creación de la Secuencia PAC_AHORRO_RETIROS_DAILY_SEQ RETIROS SARIAS

   EXECUTE IMMEDIATE 'DROP SEQUENCE PAC_AHORRO_RETIROS_DAILY_SEQ';

   EXECUTE IMMEDIATE
         'CREATE SEQUENCE PAC_AHORRO_RETIROS_DAILY_SEQ '
      || 'START WITH 1 '
      || 'INCREMENT BY 1 '
      || 'NOCACHE '
      || 'NOCYCLE';
      
      
    --Borrado y Creación de la secuencia PAC_VISITS_CONTROL_SEQ.
    
    EXECUTE IMMEDIATE 'DROP SEQUENCE APPS.PAC_VISITS_CONTROL_SEQ';
    
    EXECUTE IMMEDIATE 
          'CREATE SEQUENCE APPS.PAC_VISITS_CONTROL_SEQ '
       || 'START WITH 1 '
       || 'MAXVALUE 30 '
       || 'MINVALUE 1 '
       || 'NOCYCLE '
       || 'NOCACHE '
       || 'NOORDER ';
          
      
END;