SELECT FFVS.FLEX_VALUE_SET_ID,
       FFVS.FLEX_VALUE_SET_NAME,
       FFV.FLEX_VALUE_ID,
       FFV.FLEX_VALUE,
       FFVT.DESCRIPTION
  FROM FND_FLEX_VALUE_SETS FFVS,
       FND_FLEX_VALUES     FFV,
       FND_FLEX_VALUES_TL  FFVT
 WHERE 1 = 1
   AND FFVS.FLEX_VALUE_SET_NAME = 'PAC_MOVILIZACION_HUEVO'
   AND FFV.FLEX_VALUE_SET_ID = FFVS.FLEX_VALUE_SET_ID
   AND FFV.FLEX_VALUE_ID = FFVT.FLEX_VALUE_ID
   AND FFVT.LANGUAGE = USERENV('LANG')  
   AND FFV.ENABLED_FLAG = 'Y';