CREATE OR REPLACE VIEW PAC_RUN_TYPES_V AS
    SELECT DISTINCT
           PAA.RUN_TYPE_ID          AS  "RUN_TYPE_ID",
           PRTF.RUN_TYPE_NAME       AS  "RUN_TYPE_NAME",
           PTP.PERIOD_NAME          AS  "PERIOD_NAME",
           PPA.CONSOLIDATION_SET_ID AS  "CONSOLIDATION_SET_ID" 
      FROM PER_TIME_PERIODS         PTP,
           PAY_PAYROLLS_F           PPF,
           PAY_PAYROLL_ACTIONS      PPA,
           PAY_ASSIGNMENT_ACTIONS   PAA,
           PAY_RUN_TYPES_F          PRTF 
     WHERE 1 = 1
    --   AND PTP.PERIOD_NAME= :P_PERIOD_NAME 
       AND PTP.PAYROLL_ID = PPF.PAYROLL_ID 
       AND PPF.PAYROLL_ID = PPA.PAYROLL_ID
       AND PTP.TIME_PERIOD_ID = PPA.TIME_PERIOD_ID
    --   AND PPA.CONSOLIDATION_SET_ID = :P_CONSOLIDATION_SET_ID
       AND PPA.PAYROLL_ACTION_ID = PAA.PAYROLL_ACTION_ID
       AND PRTF.RUN_TYPE_ID = PAA.RUN_TYPE_ID;