CREATE TABLE PAC_PER_IMAGES_TB
(
  PERSON_ID         NUMBER(15),
  EMPLOYEE_NUMBER   NUMBER(15),
  EMPLOYEE_PICTURE  BLOB   DEFAULT EMPTY_BLOB()
)
LOB(EMPLOYEE_PICTURE) STORE AS (TABLESPACE IMAGES_EXAMPLE);
