CREATE OR REPLACE PACKAGE BODY PAC_HR_APPLICATION_ANDROID_PKG
IS

    FUNCTION GET_EMPLOYEE_NAME(P_EMPLOYEE_NUMBER  NUMBER)
             RETURN VARCHAR2
    IS
        var_employee_name   VARCHAR2(100) := '';
    BEGIN
    
        SELECT DISTINCT
               PAPF.FULL_NAME
          INTO var_employee_name
          FROM PER_ALL_PEOPLE_F PAPF
         WHERE 1 = 1
           AND PAPF.EMPLOYEE_NUMBER = P_EMPLOYEE_NUMBER
           AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE;
    
        RETURN var_employee_name;
    END;
             
    FUNCTION GET_DEPARTMENT(P_EMPLOYEE_NUMBER  NUMBER)
             RETURN VARCHAR2
    IS
        var_department  VARCHAR2(1000) := '';    
    BEGIN
        SELECT DISTINCT
               HOU.NAME
          INTO var_department
          FROM HR_ORGANIZATION_UNITS        HOU,
               PER_ALL_ASSIGNMENTS_F        PAAF,
               PER_ALL_PEOPLE_F             PAPF
         WHERE 1 = 1
           AND HOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
           AND PAAF.PERSON_ID = PAPF.PERSON_ID
           AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
           AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
           AND PAPF.EMPLOYEE_NUMBER = P_EMPLOYEE_NUMBER
           AND ROWNUM = 1;
           
        RETURN var_department;
    END;
             
    FUNCTION GET_JOB(P_EMPLOYEE_NUMBER  NUMBER)
             RETURN VARCHAR2
    IS
        var_job  VARCHAR2(1000) := '';
    BEGIN
        SELECT DISTINCT
               HAPD.NAME
          INTO var_job
          FROM HR_ALL_POSITIONS_D           HAPD,
               PER_ALL_ASSIGNMENTS_F        PAAF,
               PER_ALL_PEOPLE_F             PAPF
         WHERE 1 = 1
           AND HAPD.POSITION_ID = PAAF.POSITION_ID
           AND PAAF.PERSON_ID = PAPF.PERSON_ID
           AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
           AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
           AND PAPF.EMPLOYEE_NUMBER = P_EMPLOYEE_NUMBER
           AND ROWNUM = 1;
    
        RETURN var_job;
    END;
             
    FUNCTION GET_PICTURE(P_EMPLOYEE_NUMBER  NUMBER)
             RETURN BLOB
    IS
    BEGIN
        RETURN NULL;
    END;

END PAC_HR_APPLICATION_ANDROID_PKG;