CREATE OR REPLACE VIEW INFO_PERSON
AS
SELECT 
       PAPF.FULL_NAME       AS  EMPLOYEE_NAME,
       PAPF.EMPLOYEE_NUMBER AS  EMPLOYEE_NUMBER,
       HOU.NAME             AS  DEPARTMENT_NAME,
       HAPD.NAME            AS  POSITION_NAME
  FROM PER_ALL_PEOPLE_F         PAPF,
  JOIN PER_ALL_ASSIGNMENTS_F    PAAF ON PAAF.PERSON_ID = PAPF.PERSON_ID
  JOIN HR_ORGANIZATION_UNITS    HOU ON HOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
  JOIN HR_ALL_POSITIONS_D       HAPD ON PAAF.POSITION_ID = NVL(HAPD.POSITION_ID, PAAF.POSITION_ID)
 WHERE 1 = 1
   AND PAPF.EMPLOYEE_NUMBER = :P_EMPLOYEE_NUMBER
   AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
   AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND ROWNUM = 1;


SELECT EMPLOYEE_NAME,
       EMPLOYEE_NUMBER,
       DEPARTMENT_NAME,
       POSITION_NAME,
       EMPLOYEE_IMAGE
  FROM INFO_PERSON
 WHERE EMPLOYEE_NUMBER = 3166
   AND ROWNUM = 1;
   
   SELECT EMPLOYEE_NAME, EMPLOYEE_NUMBER, DEPARTMENT_NAME, POSITION_NAME, EMPLOYEE_IMAGE FROM INFO_PERSON WHERE EMPLOYEE_NUMBER = 3166 AND ROWNUM = 1