SELECT DISTINCT
       D.COMPANY_NAME,
       D.PERIOD_TYPE,
       D.PAYROLL_ID,
       D.ABREVIATE_PERIOD_TYPE,
       D.PAYROLL_NAME,
       D.PERSON_ID,
       D.MEMBER_ID,
       D.EMPLOYEE_NUMBER,
       D.EMPLOYEE_FULL_NAME,
       D.EFFECTIVE_START_DATE,
       D.IS_SAVER,
       D.IS_SAVER_DESC,
       NVL(D.AMOUNT_TO_SAVE, 0)                                     AS  AMOUNT_TO_SAVE,    
       NVL((SELECT SUM(ASST.CREDIT_AMOUNT)
              FROM ATET_SB_SAVINGS_TRANSACTIONS ASST
             WHERE 1 = 1
               AND ASST.MEMBER_ID = D.MEMBER_ID
               AND ASST.MEMBER_ACCOUNT_ID = ASMA.MEMBER_ACCOUNT_ID
               AND ASST.ELEMENT_NAME = 'D071_CAJA DE AHORRO'), 0)   AS  PAYROLL_CONTRIBUTION,
       NVL((SELECT SUM(ASST.CREDIT_AMOUNT)
              FROM ATET_SB_SAVINGS_TRANSACTIONS ASST
             WHERE 1 = 1
               AND ASST.MEMBER_ID = D.MEMBER_ID
               AND ASST.MEMBER_ACCOUNT_ID = ASMA.MEMBER_ACCOUNT_ID
               AND ASST.ELEMENT_NAME = 'APORTACION VOLUNTARIA'), 0) AS  VOLUNTARY_CONTRIBUTION,   
       NVL((SELECT SUM(ASST.DEBIT_AMOUNT)
              FROM ATET_SB_SAVINGS_TRANSACTIONS ASST
             WHERE 1 = 1
               AND ASST.MEMBER_ID = D.MEMBER_ID
               AND ASST.MEMBER_ACCOUNT_ID = ASMA.MEMBER_ACCOUNT_ID
               AND ASST.ELEMENT_NAME = 'RETIRO DE AHORRO'), 0)      AS  SAVING_RETIREMENT,             
       NVL(ASMA.FINAL_BALANCE, 0)                                   AS  FINAL_BALANCE      
  FROM (SELECT UPPER(FLV1.MEANING)      AS  COMPANY_NAME,
               (CASE 
                 WHEN PPF.PERIOD_TYPE = 'Week' OR PPF.PERIOD_TYPE = 'Semana' THEN 'S'
                 WHEN PPF.PERIOD_TYPE = 'Quincena' OR PPF.PERIOD_TYPE = 'Semi-Month' THEN 'Q'
                END)                    AS  ABREVIATE_PERIOD_TYPE,
               PPF.PERIOD_TYPE,
               PPF.PAYROLL_ID,
               PPF.PAYROLL_NAME,
               ASM.MEMBER_ID,
               ASM.PERSON_ID,
               ASM.EMPLOYEE_NUMBER,
               ASM.EMPLOYEE_FULL_NAME,
               PAC_RESULT_VALUES_PKG.GET_EFFECTIVE_START_DATE(ASM.PERSON_ID)                   AS  EFFECTIVE_START_DATE,
               ASM.IS_SAVER,
               (CASE 
                 WHEN ASM.IS_SAVER = 'N' THEN 'No'
                 WHEN ASM.IS_SAVER = 'Y' THEN 'Si'
                END)                    AS  IS_SAVER_DESC,
               ASM.AMOUNT_TO_SAVE
          FROM ATET_SB_MEMBERS      ASM,
               PER_ASSIGNMENTS_F    PAF,
               PAY_PAYROLLS_F       PPF,
               FND_LOOKUP_VALUES    FLV1
         WHERE 1 = 1
           AND ASM.PERSON_ID = PAF.PERSON_ID
           AND PAF.PAYROLL_ID = PPF.PAYROLL_ID
           AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
           AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
           AND FLV1.LOOKUP_TYPE = 'NOMINAS POR EMPLEADOR LEGAL'
           AND FLV1.LANGUAGE = USERENV('LANG')
           AND FLV1.LOOKUP_CODE = SUBSTR(PPF.PAYROLL_NAME, 0, 2)
        ) D
  LEFT JOIN ATET_SB_MEMBERS_ACCOUNTS        ASMA 
         ON (ASMA.MEMBER_ID = D.MEMBER_ID
        AND ASMA.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO')
 WHERE 1 = 1
   AND APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(D.PAYROLL_NAME) = NVL(:P_PERIOD_TYPE, APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(D.PAYROLL_NAME))
   AND D.PAYROLL_ID = NVL(:P_PAYROLL_ID, D.PAYROLL_ID)
   AND D.MEMBER_ID = NVL(:P_MEMBER_ID, D.MEMBER_ID)
   AND D.IS_SAVER = NVL(:P_IS_SAVER, D.IS_SAVER)
 GROUP BY D.COMPANY_NAME,
          D.PAYROLL_ID,
          D.ABREVIATE_PERIOD_TYPE,
          D.PERIOD_TYPE,
          D.PAYROLL_NAME,
          D.PERSON_ID,
          D.MEMBER_ID,
          D.EMPLOYEE_NUMBER,
          D.EMPLOYEE_FULL_NAME,
          D.EFFECTIVE_START_DATE,
          D.IS_SAVER,
          D.IS_SAVER_DESC,
          D.AMOUNT_TO_SAVE,
          ASMA.MEMBER_ACCOUNT_ID,
          ASMA.FINAL_BALANCE;
   
 
SELECT DISTINCT ELEMENT_NAME
  FROM ATET_SB_SAVINGS_TRANSACTIONS;
   
    