#!/bin/bash
cd /var/tmp/CARGAS/CALVARIO
ftp -n 192.1.1.191 << EOF
verbose off
prompt off
passive off
user developer oracle
cd /var/tmp/CARGAS/CALVARIO
mget *.txt *.txt
bye
EOF
ftp -n 192.1.1.191 << EOF
verbose off
prompt off
passive off
user developer oracle
cd /var/tmp/CARGAS/CALVARIO
cp *.txt /var/tmp/CARGAS/CALVARIO/Respaldo_CFD
mdelete *.txt
bye
EOF
cd /var/tmp/CARGAS/CALVARIO
ftp -n 192.1.1.119 << EOF
verbose off
prompt off
passive off
user cfd Facturacion01
cd /
mput *.txt *.txt
bye
EOF
ftp -n 192.1.1.191 << EOF
verbose off
prompt off
passive off
user developer oracle
cd /var/tmp/CARGAS/CALVARIO/Respaldo_CFD
mput *.txt *.txt
bye
EOF
rm *.txt
