SELECT *
  FROM XXCALV_VAC_EVENTOS_DET   VED,
       XXCALV_VAC_EVENTOS       VE
 WHERE 1 = 1
   AND VED.ID_EVENTO = VE.ID_EVENTO
   AND VE.PERSON_ID = 2017;
   
   
SELECT ID_EVENTO
  FROM XXCALV_VAC_EVENTOS   VE
 WHERE 1 = 1
   AND VE.PERSON_ID = 2017