SELECT *
  FROM PAC_CUST_ACCOUNT_BI_DATA;
  
  
  
  
  
SELECT HCA.CUST_ACCOUNT_ID, 
       HCA.PARTY_ID, 
       HCA.ACCOUNT_NUMBER,
       HP.PARTY_NUMBER,
       HP.PARTY_NAME,
       HCAS.ORG_ID,
       HOU.NAME
  FROM HZ_CUST_ACCOUNTS         HCA,
       HZ_PARTIES               HP,
       HZ_CUST_ACCT_SITES_ALL   HCAS,
       HR_ORGANIZATION_UNITS   HOU
 WHERE 1 = 1
   AND HCA.PARTY_ID = HP.PARTY_ID
   AND HCAS.CUST_ACCOUNT_ID = HCA.CUST_ACCOUNT_ID
   AND HCAS.ORG_ID = HOU.ORGANIZATION_ID
   AND HOU.NAME LIKE 'UO CEDIS%';
   
   
   
   
   
SELECT HOU.ORGANIZATION_ID,
       HOU.NAME
  FROM HR_ORGANIZATION_UNITS    HOU
 WHERE 1 = 1
   AND HOU.NAME LIKE 'UO CEDIS%'
   AND HOU.ORGANIZATION_ID = :ORGANIZATION_ID;   
   
   
   
   
SELECT HCA.CUST_ACCOUNT_ID, 
       HCA.PARTY_ID, 
       HCA.ACCOUNT_NUMBER
  FROM HZ_CUST_ACCOUNTS         HCA,
       HZ_PARTIES               HP,
       HZ_CUST_ACCT_SITES_ALL   HCAS,
       HR_ORGANIZATION_UNITS   HOU
 WHERE 1 = 1
   AND HCA.PARTY_ID = HP.PARTY_ID
   AND HCAS.CUST_ACCOUNT_ID = HCA.CUST_ACCOUNT_ID
   AND HCAS.ORG_ID = HOU.ORGANIZATION_ID
   AND HOU.NAME LIKE 'UO CEDIS%'
   AND HOU.ORGANIZATION_ID = :ORGANIZATION_ID;   
   
   
   
SELECT DISTINCT
       PCA.GERENCIA
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;  
   
   
SELECT DISTINCT
       PCA.CADENA
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;    
   
SELECT DISTINCT
       PCA.CLIENTE
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;  
  
 
SELECT DISTINCT
       PCA.ZONA
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;
   
SELECT DISTINCT
       PCA.CANAL
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;
   
   
SELECT DISTINCT
       PCA.DESCRIPCION_CANAL
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID;
   
   
   
   
SELECT DISTINCT
       PCA.DETALLE_CANAL
  FROM PAC_CUST_ACCOUNT_BI_DATA PCA
 WHERE 1 = 1
   AND ORGANIZATION_ID = :ORGANIZATION_ID   ;
   
   
   
SELECT *
  FROM PAC_CUST_ACCOUNT_BI_DATA
  ORDER BY CREATION_DATE DESC   