SELECT *
  FROM PAC_CUST_ACCOUNT_BI_DATA;
  
  
  
  
  
SELECT HCA.CUST_ACCOUNT_ID, 
       HCA.PARTY_ID, 
       HCA.ACCOUNT_NUMBER,
       HP.PARTY_NUMBER,
       HP.PARTY_NAME,
       HCAS.ORG_ID,
       HOU.NAME
  FROM HZ_CUST_ACCOUNTS         HCA,
       HZ_PARTIES               HP,
       HZ_CUST_ACCT_SITES_ALL   HCAS,
       HR_ORGANIZATION_UNITS   HOU
 WHERE 1 = 1
   AND HCA.PARTY_ID = HP.PARTY_ID
   AND HCAS.CUST_ACCOUNT_ID = HCA.CUST_ACCOUNT_ID
   AND HCAS.ORG_ID = HOU.ORGANIZATION_ID
   AND HOU.NAME LIKE 'UO CEDIS%';
   
  
  