ALTER SESSION SET CURRENT_SCHEMA=APPS;


SELECT /*+ LEADING(PAPF, PAAF, PPF, PPA, PTP, PPG, HAPF, PPD, HOU, PAA, PRR, PRRV) */ 
       FLV_C.LOOKUP_CODE                    AS  COMPANIA_CLAVE,
       FLV_C.MEANING                        AS  COMPANIA_NOMBRE,  
       PPG.SEGMENT1                         AS  AREA_CLAVE,
       FFVT_A.DESCRIPTION                   AS  AREA_NOMBRE,  
       FFV_G.FLEX_VALUE                     AS  GERENCIA_CLAVE,
       FFVT_G.DESCRIPTION                   AS  GERENCIA_NOMBRE,
       FFV_D.FLEX_VALUE                     AS  DEPTO_CLAVE,
       FFVT_D.DESCRIPTION                   AS  DEPTO_NOMBRE,
       FFV_CC.FLEX_VALUE                    AS  CCOSTO_CLAVE,
       FFVT_CC.DESCRIPTION                  AS  CCOSTO_NOMBRE,  
       PPD.SEGMENT3                         AS  PUESTO_CLAVE,
       PPD.SEGMENT2                         AS  PUESTO_DEPTO,
       PPD.SEGMENT1                         AS  PUESTO_NOMBRE,
       PCS.CONSOLIDATION_SET_NAME           AS  "NOMINA_CONCEPTO",
       (CASE
            WHEN PETF.ELEMENT_NAME LIKE 'D0%' OR
                 PETF.ELEMENT_NAME LIKE 'P0%' THEN
                 SUBSTR(PETF.ELEMENT_NAME, 0, 4)
            ELSE PETF.ELEMENT_NAME
        END)                                AS  "NOMINA_CLAVE",
       (CASE
            WHEN PETF.ELEMENT_NAME LIKE 'D0%' OR
                 PETF.ELEMENT_NAME LIKE 'P0%' THEN
                 SUBSTR(PETF.ELEMENT_NAME, 6)
            ELSE PETF.ELEMENT_NAME
        END)                                AS  NOMINA_ELEMENTO,
       PPA.EFFECTIVE_DATE                   AS  NOMINA_FECHA,
       PPF.PERIOD_TYPE                      AS  NOMINA_TIPOPERIODO,
       (PTP.END_DATE+1) - PTP.START_DATE    AS  NOMINA_DIAS,
       PAPF.EMPLOYEE_NUMBER                 AS  EMPLEADO_NUMERO,    
       PAPF.FULL_NAME                       AS  EMPLEADO_NOMBRE,
       PAPF.SEX                             AS  EMPLEADO_SEXO,
       PAPF.DATE_OF_BIRTH                   AS  EMPLEADO_FNACIMIENTO,
       SUM(PRRV.RESULT_VALUE)               AS  NOMINA_MONTO,
       (SELECT SUM(PPP.VALUE)
          FROM PAY_PAYROLL_ACTIONS          PPA_PP,
               PAY_ASSIGNMENT_ACTIONS       PAA_PP,
               PAY_PRE_PAYMENTS             PPP
         WHERE 1 = 1
           AND PCS.CONSOLIDATION_SET_ID = PPA_PP.CONSOLIDATION_SET_ID
           AND PPA.EFFECTIVE_DATE = PPA_PP.EFFECTIVE_DATE
           AND PPA_PP.PAYROLL_ACTION_ID = PAA_PP.PAYROLL_ACTION_ID
           AND PAA_PP.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
           AND PAA_PP.ASSIGNMENT_ACTION_ID = PPP.ASSIGNMENT_ACTION_ID
           AND PPA_PP.ACTION_TYPE IN ('P')
        )                       AS  NOMINA_TOTAL_PAGADO
  FROM PER_ALL_PEOPLE_F             PAPF,
       PER_ALL_ASSIGNMENTS_F        PAAF,
       PAY_ALL_PAYROLLS_F           PPF,
       PAY_PAYROLL_ACTIONS          PPA,
       PER_TIME_PERIODS             PTP,
       PAY_PEOPLE_GROUPS            PPG,
       HR_ALL_POSITIONS_F           HAPF,
       PER_POSITION_DEFINITIONS     PPD,
       HR_ALL_ORGANIZATION_UNITS    HOU,
       PAY_ASSIGNMENT_ACTIONS       PAA,
       PAY_RUN_RESULTS              PRR,
       PAY_RUN_RESULT_VALUES        PRRV,
       PAY_INPUT_VALUES_F           PIVF,
       PAY_ELEMENT_TYPES_F          PETF,
       PAY_ELEMENT_CLASSIFICATIONS  PEC,
       FND_LOOKUP_VALUES            FLV_C,
       FND_FLEX_VALUE_SETS          FFVS_A,
       FND_FLEX_VALUES              FFV_A,
       FND_FLEX_VALUES_TL           FFVT_A,
       FND_FLEX_VALUE_SETS          FFVS_G,
       FND_FLEX_VALUES              FFV_G,
       FND_FLEX_VALUES_TL           FFVT_G,
       FND_FLEX_VALUE_SETS          FFVS_D,
       FND_FLEX_VALUES              FFV_D,
       FND_FLEX_VALUES_TL           FFVT_D,
       FND_FLEX_VALUE_SETS          FFVS_CC,
       FND_FLEX_VALUES              FFV_CC,
       FND_FLEX_VALUES_TL           FFVT_CC,
       PAY_CONSOLIDATION_SETS       PCS
 WHERE 1 = 1
   AND PAPF.EMPLOYEE_NUMBER = 1730
   AND PPA.EFFECTIVE_DATE BETWEEN TO_DATE('06/03/2017', 'DD/MM/RRRR')
                              AND TO_DATE('20/03/2017', 'DD/MM/RRRR')
   AND PAPF.PERSON_ID = PAAF.PERSON_ID
   AND PPF.PAYROLL_ID = PAAF.PAYROLL_ID
   AND PPA.PAYROLL_ID = PPF.PAYROLL_ID
   AND PTP.PAYROLL_ID = PPF.PAYROLL_ID
   AND PPA.TIME_PERIOD_ID = PTP.TIME_PERIOD_ID
   AND PPG.PEOPLE_GROUP_ID = PAAF.PEOPLE_GROUP_ID
   AND HAPF.POSITION_ID = PAAF.POSITION_ID
   AND PPD.POSITION_DEFINITION_ID = HAPF.POSITION_DEFINITION_ID
   AND HOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
   AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
   AND PAA.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
   AND PRR.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID
   AND PRRV.RUN_RESULT_ID = PRR.RUN_RESULT_ID
   AND PPA.EFFECTIVE_DATE BETWEEN PAPF.EFFECTIVE_START_DATE
                              AND PAPF.EFFECTIVE_END_DATE
   AND PPA.EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE
                              AND PAAF.EFFECTIVE_END_DATE
   AND PPA.EFFECTIVE_DATE BETWEEN PPF.EFFECTIVE_START_DATE
                              AND PPF.EFFECTIVE_END_DATE
   AND PPA.EFFECTIVE_DATE BETWEEN HAPF.EFFECTIVE_START_DATE
                              AND HAPF.EFFECTIVE_END_DATE
   AND PIVF.INPUT_VALUE_ID = PRRV.INPUT_VALUE_ID
   AND PIVF.NAME = 'Pay Value'
   AND PPA.EFFECTIVE_DATE BETWEEN PIVF.EFFECTIVE_START_DATE
                              AND PIVF.EFFECTIVE_END_DATE
   AND PETF.ELEMENT_TYPE_ID = PRR.ELEMENT_TYPE_ID
   AND PPA.EFFECTIVE_DATE BETWEEN PETF.EFFECTIVE_START_DATE
                              AND PETF.EFFECTIVE_END_DATE   
   AND PEC.CLASSIFICATION_ID = PETF.CLASSIFICATION_ID
   AND (   PETF.ELEMENT_NAME IN (SELECT MEANING
                                   FROM FND_LOOKUP_VALUES
                                  WHERE 1 = 1
                                    AND LOOKUP_TYPE IN ('XX_PERCEPCIONES_INFORMATIVAS',
                                                        'XX_DEDUCCIONES_INFORMATIVAS')
                                    AND LANGUAGE = USERENV('LANG'))                     
        OR PEC.CLASSIFICATION_NAME IN ('Earnings', 
                                       'Supplemental Earnings', 
                                       'Amends', 
                                       'Imputed Earnings',
                                       'Voluntary Deductions',
                                       'Involuntary Deductions'))
   AND FLV_C.LOOKUP_TYPE = 'NOMINAS POR EMPLEADOR LEGAL'
   AND FLV_C.LOOKUP_CODE = SUBSTR(PPF.PAYROLL_NAME,0,2)
   AND FLV_C.LANGUAGE = USERENV('LANG')
   AND FFVS_A.FLEX_VALUE_SET_NAME = 'CALV_AREA'
   AND FFVS_A.FLEX_VALUE_SET_ID = FFV_A.FLEX_VALUE_SET_ID
   AND FFV_A.FLEX_VALUE_ID = FFVT_A.FLEX_VALUE_ID
   AND FFVT_A.LANGUAGE = USERENV('LANG')
   AND FFV_A.ENABLED_FLAG = 'Y'
   AND FFV_A.FLEX_VALUE = PPG.SEGMENT1
   AND FFVS_G.FLEX_VALUE_SET_NAME = 'CALV_GERENCIAS'
   AND FFVS_G.FLEX_VALUE_SET_ID = FFV_G.FLEX_VALUE_SET_ID
   AND FFV_G.FLEX_VALUE_ID = FFVT_G.FLEX_VALUE_ID
   AND FFVT_G.LANGUAGE = USERENV('LANG')
   AND FFV_G.ENABLED_FLAG = 'Y'
   AND FFV_G.FLEX_VALUE = PPG.SEGMENT2
   AND FFVS_D.FLEX_VALUE_SET_NAME = 'XXCALV_DEPA'
   AND FFV_D.FLEX_VALUE_SET_ID = FFVS_D.FLEX_VALUE_SET_ID
   AND FFV_D.FLEX_VALUE_ID = FFVT_D.FLEX_VALUE_ID
   AND FFVT_D.LANGUAGE = USERENV('LANG')
   AND FFV_D.ENABLED_FLAG = 'Y'
   AND FFV_D.FLEX_VALUE = PPD.SEGMENT2 
   AND FFVS_CC.FLEX_VALUE_SET_NAME = 'CC_ CALVARIO'
   AND FFV_CC.FLEX_VALUE_SET_ID = FFVS_CC.FLEX_VALUE_SET_ID
   AND FFV_CC.FLEX_VALUE_ID = FFVT_CC.FLEX_VALUE_ID
   AND FFVT_CC.LANGUAGE = USERENV('LANG')
   AND FFV_CC.ENABLED_FLAG = 'Y'
   AND FFV_CC.FLEX_VALUE = HOU.ATTRIBUTE7
   AND PCS.CONSOLIDATION_SET_ID = PPA.CONSOLIDATION_SET_ID
 GROUP
    BY FLV_C.LOOKUP_CODE,
       FLV_C.MEANING,  
       PPG.SEGMENT1,
       FFVT_A.DESCRIPTION,  
       FFV_G.FLEX_VALUE,
       FFVT_G.DESCRIPTION,
       FFV_D.FLEX_VALUE,
       FFVT_D.DESCRIPTION,
       FFV_CC.FLEX_VALUE,
       FFVT_CC.DESCRIPTION,  
       PPD.SEGMENT3,
       PPD.SEGMENT2,
       PPD.SEGMENT1,
       PCS.CONSOLIDATION_SET_NAME,
       PETF.ELEMENT_NAME,
       PPA.EFFECTIVE_DATE,
       PPF.PERIOD_TYPE,
       PTP.END_DATE,
       PTP.START_DATE,
       PAPF.EMPLOYEE_NUMBER,    
       PAPF.FULL_NAME,
       PAPF.SEX,
       PAPF.DATE_OF_BIRTH,
       PCS.CONSOLIDATION_SET_ID,
       PAAF.ASSIGNMENT_ID
 ORDER
    BY PTP.END_DATE;