    SELECT ASM.MEMBER_ID,
           ASM.PERSON_ID,
           ASM.EMPLOYEE_NUMBER,
           ASM.EMPLOYEE_FULL_NAME,
           (ASMA1.FINAL_BALANCE + ASMA2.FINAL_BALANCE) AS   FINAL_BALANCE,
           ASMA1.FINAL_BALANCE                         AS   SAVING_FINAL_BALANCE,
           ASMA2.FINAL_BALANCE                         AS   INTEREST_FINAL_BALANCE
      FROM ATET_SB_MEMBERS                  ASM,
           ATET_SB_MEMBERS_ACCOUNTS         ASMA1,
           ATET_SB_MEMBERS_ACCOUNTS         ASMA2,
           PER_ASSIGNMENTS_F                PAF,
           PAY_PERSONAL_PAYMENT_METHODS_F   PPM,
           PAY_ORG_PAYMENT_METHODS_F        OPM
     WHERE 1 = 1
       AND ASM.MEMBER_ID = ASMA1.MEMBER_ID
       AND ASM.MEMBER_ID = ASMA2.MEMBER_ID
       AND ASMA1.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
       AND ASMA2.ACCOUNT_DESCRIPTION = 'INTERES GANADO'
       AND (ASMA1.FINAL_BALANCE + ASMA2.FINAL_BALANCE) > 0
       AND ASM.PERSON_ID = PAF.PERSON_ID
       AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
       AND PAF.ASSIGNMENT_ID = PPM.ASSIGNMENT_ID
       AND SYSDATE BETWEEN PPM.EFFECTIVE_START_DATE AND PPM.EFFECTIVE_END_DATE
       AND OPM.ORG_PAYMENT_METHOD_ID = PPM.ORG_PAYMENT_METHOD_ID
       AND SYSDATE BETWEEN OPM.EFFECTIVE_START_DATE AND OPM.EFFECTIVE_END_DATE
       AND OPM.ORG_PAYMENT_METHOD_NAME LIKE '%EFECTIVO%'
     ORDER BY 5 DESC;
        
     
     
    SELECT ASM.MEMBER_ID,
           ASM.EMPLOYEE_NUMBER,
           ASM.EMPLOYEE_FULL_NAME
      FROM ATET_SB_MEMBERS                  ASM,
           ATET_SB_MEMBERS_ACCOUNTS         ASMA1,
           ATET_SB_MEMBERS_ACCOUNTS         ASMA2
     WHERE 1 = 1
       AND ASM.MEMBER_ID = ASMA1.MEMBER_ID
       AND ASM.MEMBER_ID = ASMA2.MEMBER_ID
       AND ASMA1.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
       AND ASMA2.ACCOUNT_DESCRIPTION = 'INTERES GANADO'
       AND (ASMA1.FINAL_BALANCE + ASMA2.FINAL_BALANCE) > 0
     ORDER BY 2 ;