ATET_SB_CHECKS_ALL
ATET_XLA_LINES
ATET_XLA_HEADERS
ATET_SB_SAVINGS_TRANSACTIONS
ATET_SB_MEMBERS_ACCOUNTS
ATET_CURRENCY_DISTRIBUTION_TB


SELECT *
  FROM ATET_SB_CHECKS_ALL
 ORDER BY CREATION_DATE DESC; 
 
SELECT *
  FROM ATET_XLA_HEADERS
 ORDER BY CREATION_DATE DESC; 
 
SELECT SUM(ACCOUNTED_DR),
       SUM(ACCOUNTED_CR)
  FROM ATET_XLA_LINES
 WHERE 1 = 1 
   AND HEADER_ID = 6489;
   
SELECT *
  FROM ATET_SB_SAVINGS_TRANSACTIONS
 ORDER BY CREATION_DATE DESC;
   
DELETE FROM ATET_SB_CHECKS_ALL WHERE 1 = 1 AND CHECK_ID = 1012;
DELETE FROM ATET_XLA_LINES WHERE 1 = 1 AND HEADER_ID = 6492;
DELETE FROM ATET_XLA_HEADERS WHERE 1 = 1 AND HEADER_ID = 6492;
DELETE FROM ATET_SB_SAVINGS_TRANSACTIONS WHERE 1 = 1 AND TO_DATE(CREATION_DATE, 'DD/MM/RRRR') = TO_DATE('27/07/2016', 'DD/MM/RRRR'); 
COMMIT;


DECLARE
    CURSOR DETAILS IS
    SELECT MEMBER_ID,
           ACCOUNT_DESCRIPTION,
           SAVING_RETIREMENT
      FROM ATET_CURRENCY_DISTRIBUTION_TB
     WHERE 1 = 1;
BEGIN
    FOR detail IN DETAILS LOOP
        UPDATE ATET_SB_MEMBERS_ACCOUNTS
           SET DEBIT_BALANCE = DEBIT_BALANCE - detail.SAVING_RETIREMENT,
               FINAL_BALANCE = FINAL_BALANCE + detail.SAVING_RETIREMENT
         WHERE 1 = 1
           AND MEMBER_ID = detail.MEMBER_ID
           AND ACCOUNT_DESCRIPTION = detail.ACCOUNT_DESCRIPTION;
    END LOOP;
END;

DELETE FROM ATET_CURRENCY_DISTRIBUTION_TB;


SELECT ASM.MEMBER_ID,
                       ASM.PERSON_ID,
                       ASM.EMPLOYEE_NUMBER,
                       ASM.EMPLOYEE_FULL_NAME,
                       (ASMA1.FINAL_BALANCE + ASMA2.FINAL_BALANCE) AS   FINAL_BALANCE,
                       ASMA1.FINAL_BALANCE                         AS   SAVING_FINAL_BALANCE,
                       ASMA1.MEMBER_ACCOUNT_ID                     AS   SAVING_ACCOUNT_ID,
                       ASMA1.ACCOUNT_DESCRIPTION                   AS   SAVING_ACCOUNT_DESCRIPTION,
                       ASMA2.FINAL_BALANCE                         AS   INTEREST_FINAL_BALANCE,
                       ASMA2.MEMBER_ACCOUNT_ID                     AS   INTEREST_ACCOUNT_ID,
                       ASMA2.ACCOUNT_DESCRIPTION                   AS   INTEREST_ACCOUNT_DESCRIPTION
                  FROM ATET_SB_MEMBERS                  ASM,
                       ATET_SB_MEMBERS_ACCOUNTS         ASMA1,
                       ATET_SB_MEMBERS_ACCOUNTS         ASMA2,
                       PER_ASSIGNMENTS_F                PAF,
                       PAY_PERSONAL_PAYMENT_METHODS_F   PPM,
                       PAY_ORG_PAYMENT_METHODS_F        OPM
                 WHERE 1 = 1
                   AND ASM.MEMBER_ID = ASMA1.MEMBER_ID
                   AND ASM.MEMBER_ID = ASMA2.MEMBER_ID
                   AND ASMA1.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
                   AND ASMA2.ACCOUNT_DESCRIPTION = 'INTERES GANADO'
                   AND (ASMA1.FINAL_BALANCE + ASMA2.FINAL_BALANCE) > 0
                   AND ASM.PERSON_ID = PAF.PERSON_ID
                   AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
                   AND PAF.ASSIGNMENT_ID = PPM.ASSIGNMENT_ID
                   AND SYSDATE BETWEEN PPM.EFFECTIVE_START_DATE AND PPM.EFFECTIVE_END_DATE
                   AND OPM.ORG_PAYMENT_METHOD_ID = PPM.ORG_PAYMENT_METHOD_ID
                   AND SYSDATE BETWEEN OPM.EFFECTIVE_START_DATE AND OPM.EFFECTIVE_END_DATE
                   AND OPM.ORG_PAYMENT_METHOD_NAME LIKE '%EFECTIVO%';