SELECT DISTINCT
       PRO.PAYROLL_ID,
       PRO.PAYROLL_NAME,
       PAC.ASSIGNMENT_SET_ID,
       PTP.PERIOD_NAME,
       PAC.CONSOLIDATION_SET_ID,
       PTP.END_DATE
  FROM PAY_PAYROLLS_F           PRO,
       PAY_PAYROLL_ACTIONS      PAC,
       PER_TIME_PERIODS         PTP,
--       PAY_ASSIGNMENT_ACTIONS   AAC,       
       PER_ALL_ASSIGNMENTS_F    PA
--       PER_PEOPLE_F            PEO,
--       HR_ORGANIZATION_UNITS    HRAOU  
 WHERE 1 = 1
   AND PAC.PAYROLL_ID = PRO.PAYROLL_ID
   AND PAC.PAYROLL_ID = PTP.PAYROLL_ID
   AND PAC.TIME_PERIOD_ID = PTP.TIME_PERIOD_ID
   AND PA.PAYROLL_ID = PRO.PAYROLL_ID
--   AND PAC.PAYROLL_ACTION_ID =  AAC.PAYROLL_ACTION_ID
--   AND PA.PERSON_ID = PEO.PERSON_ID  
--   AND PA.ORGANIZATION_ID = HRAOU.ORGANIZATION_ID  
   AND PA.PAYROLL_ID = :P_PAYROLL_ID
   AND PTP.END_DATE = NVL(:P_END_DATE, PTP.END_DATE) 
   AND PAC.CONSOLIDATION_SET_ID = NVL(:P_CONSOLIDATION_SET_ID, PAC.CONSOLIDATION_SET_ID)      
--   AND PEO.PERSON_ID = NVL(:P_PERSON_ID, PEO.PERSON_ID)
--   AND HRAOU.NAME = NVL(:P_ORGANIZATION_NAME,HRAOU.NAME)      