    SELECT DISTINCT
           CII.INSTANCE_NUMBER      AS VEHICLE_ID,
           CII.INSTANCE_DESCRIPTION AS VEHICLE,
           PAC_FUEL_EC_REPORTS_PKG.GET_TRIP_DISTANCE_BY_MONTH(CII.INSTANCE_NUMBER, :P_YEAR, :P_MONTH)   AS  TRIP_DISTANCE,
           PAC_FUEL_EC_REPORTS_PKG.GET_CONSUMED_FUEL_BY_MONTH(CII.INSTANCE_NUMBER, :P_YEAR, :P_MONTH)   AS  CONSUMED_FUEL,
           PAC_FUEL_EC_REPORTS_PKG.GET_EFFICIENCY_BY_MONTH(CII.INSTANCE_NUMBER, :P_YEAR, :P_MONTH)      AS  EFFICIENCY
      FROM CSI_ITEM_INSTANCES       CII,
           EAM_ORG_MAINT_DEFAULTS   EOMD,
           MTL_EAM_LOCATIONS        MEL,
           MTL_CATEGORIES_B         MC 
     WHERE 1 = 1
       AND CII.INSTANCE_ID  = EOMD.OBJECT_ID
       AND EOMD.AREA_ID = MEL.LOCATION_ID
       AND CII.CATEGORY_ID = MC.CATEGORY_ID
       AND MC.SEGMENT1 = 'VEHICULO'
       AND MEL.LOCATION_CODES = 'REPARTO'
       AND CII.INSTANCE_NUMBER NOT LIKE 'PAC%'
       AND (MC.SEGMENT2 = 'TRACTOCAMION'
        OR MC.SEGMENT2 = 'TORTON')
     ORDER BY VEHICLE;