package xxcalv.oracle.apps.ar.PortalFacturas.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAC_MASTEREDI_REPORT_VORowImpl extends OAViewRowImpl {
    public static final int EMIANIO = 0;
    public static final int EMIMES = 1;
    public static final int EMIDIA = 2;
    public static final int EMITIONDATE = 3;
    public static final int TIPDOC = 4;
    public static final int RFCEMI = 5;
    public static final int RFCREC = 6;
    public static final int NOMREC = 7;
    public static final int SERFOL = 8;
    public static final int NUMFOL = 9;
    public static final int SUBTBR = 10;
    public static final int TOTPAG = 11;
    public static final int TOTRET = 12;
    public static final int TOTTRA = 13;
    public static final int UUID = 14;
    public static final int VERSIO = 15;
    public static final int CODMETPAG = 16;

    /**This is the default constructor (do not remove)
     */
    public PAC_MASTEREDI_REPORT_VORowImpl() {
    }

    /**Gets PAC_MASTEREDI_REPORT_EO entity object.
     */
    public PAC_MASTEREDI_REPORT_EOImpl getPAC_MASTEREDI_REPORT_EO() {
        return (PAC_MASTEREDI_REPORT_EOImpl)getEntity(0);
    }

    /**Gets the attribute value for the calculated attribute Emianio
     */
    public Number getEmianio() {
        return (Number) getAttributeInternal(EMIANIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Emianio
     */
    public void setEmianio(Number value) {
        setAttributeInternal(EMIANIO, value);
    }

    /**Gets the attribute value for the calculated attribute Emimes
     */
    public Number getEmimes() {
        return (Number) getAttributeInternal(EMIMES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Emimes
     */
    public void setEmimes(Number value) {
        setAttributeInternal(EMIMES, value);
    }

    /**Gets the attribute value for the calculated attribute Emidia
     */
    public Number getEmidia() {
        return (Number) getAttributeInternal(EMIDIA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Emidia
     */
    public void setEmidia(Number value) {
        setAttributeInternal(EMIDIA, value);
    }

    /**Gets the attribute value for the calculated attribute EmitionDate
     */
    public Date getEmitionDate() {
        return (Date) getAttributeInternal(EMITIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmitionDate
     */
    public void setEmitionDate(Date value) {
        setAttributeInternal(EMITIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Tipdoc
     */
    public String getTipdoc() {
        if (getAttributeInternal(TIPDOC) != null){
            return (String) getAttributeInternal(TIPDOC);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tipdoc
     */
    public void setTipdoc(String value) {
        setAttributeInternal(TIPDOC, value);
    }

    /**Gets the attribute value for the calculated attribute Rfcemi
     */
    public String getRfcemi() {
        if (getAttributeInternal(RFCEMI) != null){
            return (String) getAttributeInternal(RFCEMI);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rfcemi
     */
    public void setRfcemi(String value) {
        setAttributeInternal(RFCEMI, value);
    }

    /**Gets the attribute value for the calculated attribute Rfcrec
     */
    public String getRfcrec() {
        if (getAttributeInternal(RFCREC) != null){
            return (String) getAttributeInternal(RFCREC);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rfcrec
     */
    public void setRfcrec(String value) {
        setAttributeInternal(RFCREC, value);
    }

    /**Gets the attribute value for the calculated attribute Nomrec
     */
    public String getNomrec() {
        if (getAttributeInternal(NOMREC) != null){
            return (String) getAttributeInternal(NOMREC);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Nomrec
     */
    public void setNomrec(String value) {
        setAttributeInternal(NOMREC, value);
    }

    /**Gets the attribute value for the calculated attribute Serfol
     */
    public String getSerfol() {
        if (getAttributeInternal(SERFOL) != null){
            return (String) getAttributeInternal(SERFOL);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Serfol
     */
    public void setSerfol(String value) {
        setAttributeInternal(SERFOL, value);
    }

    /**Gets the attribute value for the calculated attribute Numfol
     */
    public String getNumfol() {
        if (getAttributeInternal(NUMFOL) != null){
            return (String) getAttributeInternal(NUMFOL);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Numfol
     */
    public void setNumfol(String value) {
        setAttributeInternal(NUMFOL, value);
    }

    /**Gets the attribute value for the calculated attribute Subtbr
     */
    public String getSubtbr() {
        if (getAttributeInternal(SUBTBR) != null){
            return (String) getAttributeInternal(SUBTBR);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Subtbr
     */
    public void setSubtbr(String value) {
        setAttributeInternal(SUBTBR, value);
    }

    /**Gets the attribute value for the calculated attribute Totpag
     */
    public String getTotpag() {
        if (getAttributeInternal(TOTPAG) != null){
            return (String) getAttributeInternal(TOTPAG);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Totpag
     */
    public void setTotpag(String value) {
        setAttributeInternal(TOTPAG, value);
    }

    /**Gets the attribute value for the calculated attribute Totret
     */
    public String getTotret() {
        if (getAttributeInternal(TOTRET) != null){
            return (String) getAttributeInternal(TOTRET);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Totret
     */
    public void setTotret(String value) {
        setAttributeInternal(TOTRET, value);
    }

    /**Gets the attribute value for the calculated attribute Tottra
     */
    public String getTottra() {
        if (getAttributeInternal(TOTTRA) != null){
            return (String) getAttributeInternal(TOTTRA);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Tottra
     */
    public void setTottra(String value) {
        setAttributeInternal(TOTTRA, value);
    }

    /**Gets the attribute value for the calculated attribute Uuid
     */
    public String getUuid() {
        if (getAttributeInternal(UUID) != null){
            return (String) getAttributeInternal(UUID);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Uuid
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**Gets the attribute value for the calculated attribute Versio
     */
    public String getVersio() {
        if (getAttributeInternal(VERSIO) != null){
            return (String) getAttributeInternal(VERSIO);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Versio
     */
    public void setVersio(String value) {
        setAttributeInternal(VERSIO, value);
    }

    /**Gets the attribute value for the calculated attribute Codmetpag
     */
    public String getCodmetpag() {
        if (getAttributeInternal(CODMETPAG) != null){
            return (String) getAttributeInternal(CODMETPAG);
        } else {
            return "";
        }
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Codmetpag
     */
    public void setCodmetpag(String value) {
        setAttributeInternal(CODMETPAG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMIANIO:
            return getEmianio();
        case EMIMES:
            return getEmimes();
        case EMIDIA:
            return getEmidia();
        case EMITIONDATE:
            return getEmitionDate();
        case TIPDOC:
            return getTipdoc();
        case RFCEMI:
            return getRfcemi();
        case RFCREC:
            return getRfcrec();
        case NOMREC:
            return getNomrec();
        case SERFOL:
            return getSerfol();
        case NUMFOL:
            return getNumfol();
        case SUBTBR:
            return getSubtbr();
        case TOTPAG:
            return getTotpag();
        case TOTRET:
            return getTotret();
        case TOTTRA:
            return getTottra();
        case UUID:
            return getUuid();
        case VERSIO:
            return getVersio();
        case CODMETPAG:
            return getCodmetpag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
