package xxcalv.oracle.apps.ar.PortalFacturas.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAC_MASTEREDI_REPORT_EOImpl extends OAEntityImpl {
    public static final int EMIANIO = 0;
    public static final int EMIMES = 1;
    public static final int EMIDIA = 2;
    public static final int EMITIONDATE = 3;
    public static final int TIPDOC = 4;
    public static final int RFCEMI = 5;
    public static final int RFCREC = 6;
    public static final int NOMREC = 7;
    public static final int SERFOL = 8;
    public static final int NUMFOL = 9;
    public static final int SUBTBR = 10;
    public static final int TOTPAG = 11;
    public static final int TOTRET = 12;
    public static final int TOTTRA = 13;
    public static final int UUID = 14;
    public static final int VERSIO = 15;
    public static final int CODMETPAG = 16;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public PAC_MASTEREDI_REPORT_EOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxcalv.oracle.apps.ar.PortalFacturas.server.PAC_MASTEREDI_REPORT_EO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Emianio, using the alias name Emianio
     */
    public Number getEmianio() {
        return (Number)getAttributeInternal(EMIANIO);
    }


    /**Gets the attribute value for Emimes, using the alias name Emimes
     */
    public Number getEmimes() {
        return (Number)getAttributeInternal(EMIMES);
    }


    /**Gets the attribute value for Emidia, using the alias name Emidia
     */
    public Number getEmidia() {
        return (Number)getAttributeInternal(EMIDIA);
    }


    /**Gets the attribute value for Tipdoc, using the alias name Tipdoc
     */
    public String getTipdoc() {
        return (String)getAttributeInternal(TIPDOC);
    }


    /**Gets the attribute value for Rfcemi, using the alias name Rfcemi
     */
    public String getRfcemi() {
        return (String)getAttributeInternal(RFCEMI);
    }


    /**Gets the attribute value for Rfcrec, using the alias name Rfcrec
     */
    public String getRfcrec() {
        return (String)getAttributeInternal(RFCREC);
    }


    /**Gets the attribute value for Serfol, using the alias name Serfol
     */
    public String getSerfol() {
        return (String)getAttributeInternal(SERFOL);
    }


    /**Gets the attribute value for Numfol, using the alias name Numfol
     */
    public String getNumfol() {
        return (String)getAttributeInternal(NUMFOL);
    }


    /**Gets the attribute value for Totpag, using the alias name Totpag
     */
    public String getTotpag() {
        return (String)getAttributeInternal(TOTPAG);
    }


    /**Gets the attribute value for Uuid, using the alias name Uuid
     */
    public String getUuid() {
        return (String)getAttributeInternal(UUID);
    }


    /**Gets the attribute value for Versio, using the alias name Versio
     */
    public String getVersio() {
        return (String)getAttributeInternal(VERSIO);
    }


    /**Gets the attribute value for Codmetpag, using the alias name Codmetpag
     */
    public String getCodmetpag() {
        return (String)getAttributeInternal(CODMETPAG);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMIANIO:
            return getEmianio();
        case EMIMES:
            return getEmimes();
        case EMIDIA:
            return getEmidia();
        case EMITIONDATE:
            return getEmitionDate();
        case TIPDOC:
            return getTipdoc();
        case RFCEMI:
            return getRfcemi();
        case RFCREC:
            return getRfcrec();
        case NOMREC:
            return getNomrec();
        case SERFOL:
            return getSerfol();
        case NUMFOL:
            return getNumfol();
        case SUBTBR:
            return getSubtbr();
        case TOTPAG:
            return getTotpag();
        case TOTRET:
            return getTotret();
        case TOTTRA:
            return getTottra();
        case UUID:
            return getUuid();
        case VERSIO:
            return getVersio();
        case CODMETPAG:
            return getCodmetpag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    public void setLastUpdateLogin(Number n){}
    public void setLastUpdatedBy(Number n){}
    public void setLastUpdateDate(Date d){}
    public void setCreatedBy(Number n){}
    public void setCreationDate(Date d){}

    /**Gets the attribute value for EmitionDate, using the alias name EmitionDate
     */
    public Date getEmitionDate() {
        return (Date)getAttributeInternal(EMITIONDATE);
    }

    /**Gets the attribute value for Nomrec, using the alias name Nomrec
     */
    public String getNomrec() {
        return (String)getAttributeInternal(NOMREC);
    }

    /**Gets the attribute value for Subtbr, using the alias name Subtbr
     */
    public String getSubtbr() {
        return (String)getAttributeInternal(SUBTBR);
    }

    /**Gets the attribute value for Totret, using the alias name Totret
     */
    public String getTotret() {
        return (String)getAttributeInternal(TOTRET);
    }

    /**Gets the attribute value for Tottra, using the alias name Tottra
     */
    public String getTottra() {
        return (String)getAttributeInternal(TOTTRA);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(String uuid) {
        return new Key(new Object[]{uuid});
    }
}
