PACKAGE ATET_MEMBER_REGISTRATION_PKG IS
  
  PROCEDURE ENABLE_CONTROLS;
  
  PROCEDURE LOAD_FORM;
  
  PROCEDURE INSERT_MEMBER;
  
  PROCEDURE INSERT_SAVING_AMOUNT;
  
  FUNCTION COMPARAISON (val1 VARCHAR2, val2 VARCHAR2)
  RETURN NUMBER;
  
END;