SELECT DISTINCT
       MEL.LOCATION_CODES
  FROM MTL_EAM_LOCATIONS MEL
 WHERE 1 = 1
   AND MEL.LOCATION_CODES <> 'GRB'
 ORDER BY MEL.LOCATION_CODES 
 
 (SELECT DISTINCT MEL.LOCATION_CODES FROM MTL_EAM_LOCATIONS MEL WHERE 1 = 1 AND MEL.LOCATION_CODES <> 'GRB')