SELECT DISTINCT
       MC.SEGMENT2              AS VEHICLE_TYPE
  FROM MTL_CATEGORIES_B         MC 
 WHERE 1 = 1
   AND MC.SEGMENT1 = 'VEHICULO'
   AND (MC.SEGMENT2 <> 'REMOLQUE'
    AND MC.SEGMENT2 <> 'SEMIREMOLQUE'
    AND MC.SEGMENT2 <> 'TOLVA'
    AND MC.SEGMENT2 <> 'DOLLY')
 ORDER BY MC.SEGMENT2;
 
 
 (SELECT DISTINCT MC.SEGMENT2 FROM MTL_CATEGORIES_B MC WHERE 1 = 1 AND MC.SEGMENT1 = 'VEHICULO' AND (MC.SEGMENT2 <> 'REMOLQUE' AND MC.SEGMENT2 <> 'SEMIREMOLQUE' AND MC.SEGMENT2 <> 'TOLVA' AND MC.SEGMENT2 <> 'DOLLY'))