            SELECT NVL(PPOS.ADJUSTED_SVC_DATE, PPF.ORIGINAL_DATE_OF_HIRE),
                   PPF.EMPLOYEE_NUMBER,
                   PPF.FULL_NAME
              FROM PER_PEOPLE_F             PPF,
                   PER_PERIODS_OF_SERVICE   PPOS    
             WHERE 1 = 1 
               AND PPF.PERSON_ID = PPOS.PERSON_ID
               AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
               AND PPOS.ACTUAL_TERMINATION_DATE IS NULL
               AND EXTRACT(DAY FROM NVL(PPOS.ADJUSTED_SVC_DATE, PPF.ORIGINAL_DATE_OF_HIRE)) = 23
               AND EXTRACT(MONTH FROM NVL(PPOS.ADJUSTED_SVC_DATE, PPF.ORIGINAL_DATE_OF_HIRE)) = 7;
               
               
XXCALV_VAC_EVENTOS