CREATE OR REPLACE PACKAGE PAC_SALARY_PROPOSAL_PKG AS

    PROCEDURE   CHANGE_SALARY (
        P_ERRBUF    OUT NOCOPY  VARCHAR2,
        P_RETCODE   OUT NOCOPY  VARCHAR2,
        P_EMPLOYEE_NUMBER       NUMBER,
        P_SALARY                NUMBER,
        P_EFFECTIVE_DATE        VARCHAR2);
    
END PAC_SALARY_PROPOSAL_PKG;