SELECT DISTINCT ASPR.EXPORT_REQUEST_ID, ASPR.IMPORT_REQUEST_ID, '(' || ASPR.EXPORT_REQUEST_ID || ') ' || ASPR.PERIOD_NAME AS REQUEST_NAME FROM ATET_SB_PAYROLL_RESULTS ASPR
 WHERE 1 = 1
   AND ASPR.IMPORT_REQUEST_ID IS NULL
 ORDER BY ASPR.EXPORT_REQUEST_ID