SELECT ASPR.PERSON_ID,
       ASPR.ASSIGNMENT_ID,
       ASPR.ASSIGNMENT_ACTION_ID,
       ASPR.PAYROLL_ACTION_ID,
       ASPR.EARNED_DATE,
       ASPR.PERIOD_NAME,
       ASPR.PAYROLL_STATUS,
       ASPR.ELEMENT_NAME,
       ASPR.ENTRY_NAME,
       ASPR.ENTRY_UNITS,
       ASPR.ENTRY_VALUE,
       ASPR.EXPORT_REQUEST_ID
  FROM ATET_SB_PAYROLL_RESULTS ASPR
 WHERE ASPR.EXPORT_REQUEST_ID = :P_EXPORT_REQUEST_ID