CREATE TABLE ATET_MONTHS
(
    MONTH_NUMBER    NUMBER,
    MONTH_NAME      VARCHAR2(100)
);

INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (1, 'ENERO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (2, 'FEBRERO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (3, 'MARZO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (4, 'ABRIL');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (5, 'MAYO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (6, 'JUNIO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (7, 'JULIO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (8, 'AGOSTO');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (9, 'SEPTIEMBRE');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (10, 'OCTUBRE');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (11, 'NOVIEMBRE');
INSERT INTO ATET_MONTHS(MONTH_NUMBER, MONTH_NAME) VALUES (12, 'DICIEMBRE');

COMMIT;