CREATE TABLE ATET_SB_MEMBERS
(
	MEMBER_ID                  NUMBER   NOT NULL,
	SAVING_BANK_ID             NUMBER   NOT NULL,
	PERSON_ID                  NUMBER,
	EMPLOYEE_NUMBER            NUMBER,
	EMPLOYEE_FULL_NAME         VARCHAR2(250),
	PERSON_TYPE                VARCHAR2(250),
	SENIORITY_YEARS            NUMBER,
	RFC                        VARCHAR2(250),
	CURP                       VARCHAR2(250),
	SEX                        VARCHAR2(250),
	EMAIL_ADDRESS              VARCHAR2(250),
	AMOUNT_TO_SAVE             NUMBER,
	EFFECTIVE_HIRE_DATE        DATE,
	EFFECTIVE_TERMINATION_DATE DATE,
	MEMBER_START_DATE          DATE,
	MEMBER_END_DATE            DATE,
	IS_SAVER                   VARCHAR2(1),
	IS_BORROWER                VARCHAR2(1),
	IS_ENDORSEMENT             VARCHAR2(1),
	ATTRIBUTE1                 NUMBER,
	ATTRIBUTE2                 NUMBER,
	ATTRIBUTE3                 NUMBER,
	ATTRIBUTE4                 NUMBER,
	ATTRIBUTE5                 NUMBER,
	ATTRIBUTE6                 VARCHAR2(250),
	ATTRIBUTE7                 VARCHAR2(250),
	ATTRIBUTE8                 VARCHAR2(250),
	ATTRIBUTE9                 VARCHAR2(250),
	ATTRIBUTE10                VARCHAR2(250),
	ATTRIBUTE11                VARCHAR2(250),
	ATTRIBUTE12                VARCHAR2(250),
	ATTRIBUTE13                VARCHAR2(250),
	ATTRIBUTE14                VARCHAR2(250),
	ATTRIBUTE15                VARCHAR2(250),
	CREATION_DATE              DATE,
	CREATED_BY                 NUMBER,
	LAST_UPDATE_DATE           DATE,
	LAST_UPDATED_BY            NUMBER
);


ALTER TABLE ATET_SB_MEMBERS
	ADD CONSTRAINT UQ_ATET_SB_MEMBERS UNIQUE (MEMBER_ID)
 USING INDEX ;


ALTER TABLE ATET_SB_MEMBERS
    ADD CONSTRAINT FK_ATETSBMEMBERS_SAVINGBANKID
        FOREIGN KEY (SAVING_BANK_ID)
        REFERENCES ATET_SAVINGS_BANK(SAVING_BANK_ID);
        
        
CREATE SEQUENCE ATET_SB_MEMBERS_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER ATET_SB_MEMBERS_TGR
BEFORE INSERT
   ON ATET_SB_MEMBERS
   FOR EACH ROW
DECLARE

   var_next_id  NUMBER;

BEGIN

    SELECT ATET_SB_MEMBERS_SEQ.NEXTVAL
      INTO var_next_id
      FROM dual;        
      
    :NEW.MEMBER_ID := var_next_id;

END;