DROP TABLE APPS.ATET_SB_LOAN_HOLDS CASCADE CONSTRAINTS;

CREATE TABLE APPS.ATET_SB_LOAN_HOLDS
(
  LOAN_HOLD_ID       NUMBER                     NOT NULL,
  CREATION_DATE      DATE                       NOT NULL,
  CREATED_BY         NUMBER                     NOT NULL,
  LAST_UPDATE_DATE   DATE                       NOT NULL,
  LAST_UPDATED_BY    NUMBER                     NOT NULL,
  LAST_UPDATE_LOGIN  NUMBER,
  HOLD_SOURCE_ID     NUMBER                     NOT NULL,
  HOLD_RELEASE_ID    NUMBER,
  LOAN_ID            NUMBER                     NOT NULL,
  HOLD_REASON_CODE   VARCHAR2(3000 BYTE)        NOT NULL,
  HOLD_COMMENT       VARCHAR2(2000 BYTE),
  ATTRIBUTE1         NUMBER,
  ATTRIBUTE2         NUMBER,
  ATTRIBUTE3         NUMBER,
  ATTRIBUTE4         NUMBER,
  ATTRIBUTE5         NUMBER,
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE),
  ATTRIBUTE11        VARCHAR2(240 BYTE),
  ATTRIBUTE12        VARCHAR2(240 BYTE),
  ATTRIBUTE13        VARCHAR2(240 BYTE),
  ATTRIBUTE14        VARCHAR2(240 BYTE),
  ATTRIBUTE15        VARCHAR2(240 BYTE),
  RELEASED_FLAG      VARCHAR2(1 BYTE)           NOT NULL
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE ATET_SB_LOAN_HOLDS
	ADD CONSTRAINT UQ_ATET_SB_LOAN_HOLDS UNIQUE (LOAN_HOLD_ID)
 USING INDEX ;
 
 
CREATE SEQUENCE ATET_SB_LOAN_HOLDS_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER ATET_SB_LOAN_HOLDS_TGR
BEFORE INSERT
   ON ATET_SB_LOAN_HOLDS
   FOR EACH ROW
DECLARE

   var_next_id  NUMBER;

BEGIN

    SELECT ATET_SB_LOAN_HOLDS_SEQ.NEXTVAL
      INTO var_next_id
      FROM dual;        
      
    :NEW.LOAN_HOLD_ID := var_next_id;

END;