DROP VIEW APPS.ATET_ENDORSEMENTS_LOV_V;

/* Formatted on 2016/05/14 12:03 (Formatter Plus v4.8.8) */
CREATE OR REPLACE FORCE VIEW apps.atet_endorsements_lov_v (member_id,
                                                           saving_bank_id,
                                                           person_id,
                                                           employee_number,
                                                           employee_full_name,
                                                           person_type,
                                                           seniority_years,
                                                           rfc,
                                                           curp,
                                                           sex,
                                                           email_address,
                                                           amount_to_save,
                                                           effective_hire_date,
                                                           effective_termination_date,
                                                           member_start_date,
                                                           member_end_date,
                                                           is_saver,
                                                           is_borrower,
                                                           is_endorsement,
                                                           attribute1,
                                                           attribute2,
                                                           attribute3,
                                                           attribute4,
                                                           attribute5,
                                                           attribute6,
                                                           attribute7,
                                                           attribute8,
                                                           attribute9,
                                                           attribute10,
                                                           attribute11,
                                                           attribute12,
                                                           attribute13,
                                                           attribute14,
                                                           attribute15,
                                                           debit_balance,
                                                           credit_balance
                                                          )
AS
SELECT DISTINCT 
            asm."MEMBER_ID", 
            asm."SAVING_BANK_ID", 
            asm."PERSON_ID",
            asm."EMPLOYEE_NUMBER", 
            asm."EMPLOYEE_FULL_NAME",
            asm."PERSON_TYPE", 
            asm."SENIORITY_YEARS", 
            asm."RFC", 
            asm."CURP",
            asm."SEX", 
            asm."EMAIL_ADDRESS", 
            asm."AMOUNT_TO_SAVE",
            asm."EFFECTIVE_HIRE_DATE", 
            asm."EFFECTIVE_TERMINATION_DATE",
            asm."MEMBER_START_DATE", 
            asm."MEMBER_END_DATE", 
            asm."IS_SAVER",
            asm."IS_BORROWER", 
            asm."IS_ENDORSEMENT", 
            asm."ATTRIBUTE1",
            asm."ATTRIBUTE2", 
            asm."ATTRIBUTE3", 
            asm."ATTRIBUTE4",
            asm."ATTRIBUTE5", 
            asm."ATTRIBUTE6", 
            asm."ATTRIBUTE7",
            asm."ATTRIBUTE8", 
            asm."ATTRIBUTE9", 
            asm."ATTRIBUTE10",
            asm."ATTRIBUTE11", 
            asm."ATTRIBUTE12", 
            asm."ATTRIBUTE13",
            asm."ATTRIBUTE14", 
            asm."ATTRIBUTE15",
            SUM(NVL ((SELECT SUM(asma.final_balance)
                        FROM atet_sb_members_accounts asma 
                       WHERE 1 = 1
                         AND asm.member_id = asma.member_id 
                         AND asma.account_description = 'D071_CAJA DE AHORRO'), 0)) debit_balance,
            SUM(NVL ((SELECT SUM(asma1.final_balance)
                       FROM atet_sb_members_accounts asma1 
                      WHERE 1 = 1 
                        AND asm.member_id = asma1.member_id 
                        AND asma1.account_description = 'D072_PRESTAMO CAJA DE AHORRO'), 0)) credit_balance
       FROM atet_sb_members asm
      WHERE 1 = 1        
        AND saving_bank_id = atet_savings_bank_pkg.get_saving_bank_id
        
      GROUP BY asm."MEMBER_ID", 
            asm."SAVING_BANK_ID", 
            asm."PERSON_ID",
            asm."EMPLOYEE_NUMBER", 
            asm."EMPLOYEE_FULL_NAME",
            asm."PERSON_TYPE", 
            asm."SENIORITY_YEARS", 
            asm."RFC", 
            asm."CURP",
            asm."SEX", 
            asm."EMAIL_ADDRESS", 
            asm."AMOUNT_TO_SAVE",
            asm."EFFECTIVE_HIRE_DATE", 
            asm."EFFECTIVE_TERMINATION_DATE",
            asm."MEMBER_START_DATE", 
            asm."MEMBER_END_DATE", 
            asm."IS_SAVER",
            asm."IS_BORROWER", 
            asm."IS_ENDORSEMENT", 
            asm."ATTRIBUTE1",
            asm."ATTRIBUTE2", 
            asm."ATTRIBUTE3", 
            asm."ATTRIBUTE4",
            asm."ATTRIBUTE5", 
            asm."ATTRIBUTE6", 
            asm."ATTRIBUTE7",
            asm."ATTRIBUTE8", 
            asm."ATTRIBUTE9", 
            asm."ATTRIBUTE10",
            asm."ATTRIBUTE11", 
            asm."ATTRIBUTE12", 
            asm."ATTRIBUTE13",
            asm."ATTRIBUTE14", 
            asm."ATTRIBUTE15";


