CREATE TABLE ATET_SB_ENDORSEMENTS
(
	ENDORSEMENT_ID          NUMBER      NOT NULL,
	LOAN_ID                 NUMBER      NOT NULL,
    MEMBER_BORROWER_ID      NUMBER      NOT NULL,
	MEMBER_ENDORSEMENT_ID   NUMBER      NOT NULL,
	ENDORSEMENT_FLAG        VARCHAR(250),
	ATTRIBUTE1              NUMBER,
	ATTRIBUTE2              NUMBER,
	ATTRIBUTE3              NUMBER,
	ATTRIBUTE4              NUMBER,
	ATTRIBUTE5              NUMBER,
	ATTRIBUTE6              VARCHAR2(250),
	ATTRIBUTE7              VARCHAR2(250),
	ATTRIBUTE8              VARCHAR2(250),
	ATTRIBUTE9              VARCHAR2(250),
	ATTRIBUTE10             VARCHAR2(250),
	ATTRIBUTE11             VARCHAR2(250),
	ATTRIBUTE12             VARCHAR2(250),
	ATTRIBUTE13             VARCHAR2(250),
	ATTRIBUTE14             VARCHAR2(250),
	ATTRIBUTE15             VARCHAR2(250),
	CREATION_DATE           DATE,
	CREATED_BY              NUMBER,
	LAST_UPDATE_DATE        DATE,
	LAST_UPDATED_BY         NUMBER
);


ALTER TABLE ATET_SB_ENDORSEMENTS
	ADD CONSTRAINT UQ_ATET_SB_ENDORSEMENTS UNIQUE (ENDORSEMENT_ID)
 USING INDEX ;


ALTER TABLE ATET_SB_ENDORSEMENTS
    ADD CONSTRAINT FK_ATETSBEND_LOANID
        FOREIGN KEY (LOAN_ID)
        REFERENCES ATET_SB_LOANS(LOAN_ID);
        
        
ALTER TABLE ATET_SB_ENDORSEMENTS
    ADD CONSTRAINT FK_ATETSBEND_MEMBORID 
        FOREIGN KEY (MEMBER_BORROWER_ID)
        REFERENCES ATET_SB_MEMBERS(MEMBER_ID);
        
        
ALTER TABLE ATET_SB_ENDORSEMENTS
    ADD CONSTRAINT FK_ATETSBEND_MEMENDID 
        FOREIGN KEY (MEMBER_ENDORSEMENT_ID)
        REFERENCES ATET_SB_MEMBERS(MEMBER_ID);
        
        
CREATE SEQUENCE ATET_SB_ENDORSEMENTS_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER ATET_SB_ENDORSEMENTS_TGR
BEFORE INSERT
   ON ATET_SB_ENDORSEMENTS
   FOR EACH ROW
DECLARE

   var_next_id  NUMBER;

BEGIN

    SELECT ATET_SB_ENDORSEMENTS_SEQ.NEXTVAL
      INTO var_next_id
      FROM dual;        
      
    :NEW.ENDORSEMENT_ID := var_next_id;

END;