CREATE OR REPLACE VIEW ATET_SB_PERSON_VIEW
AS
SELECT D.EMPLOYEE_NUMBER,
       D.FULL_NAME,
       D.PERSON_ID
  FROM (SELECT PPF.EMPLOYEE_NUMBER,
               PPF.FULL_NAME,
               PPF.PERSON_ID
          FROM PER_PEOPLE_F PPF, PER_PERSON_TYPES_TL PPTT
         WHERE 1 = 1
           AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
           AND PPF.PERSON_TYPE_ID = PPTT.PERSON_TYPE_ID
           AND LANGUAGE = USERENV('LANG')
           AND PPTT.USER_PERSON_TYPE IN ('Employee', 'Empleado')
         ORDER BY TO_NUMBER(PPF.EMPLOYEE_NUMBER))D
  LEFT JOIN ATET_SB_MEMBERS  ASM
    ON ASM.PERSON_ID = D.PERSON_ID AND ASM.SAVING_BANK_ID = ATET_SAVINGS_BANK_PKG.GET_SAVING_BANK_ID
 WHERE 1 = 1
   AND ASM.PERSON_ID IS NULL   
 ORDER BY D.EMPLOYEE_NUMBER