CREATE TABLE ATET_SB_MEMBERS_BOARD
(
	MEMBER_BOARD_ID       NUMBER    NOT NULL,
	SAVING_BANK_ID        NUMBER    NOT NULL,
	PERSON_ID             NUMBER,
	EMPLOYEE_NUMBER       NUMBER,
	EMPLOYEE_FULL_NAME    VARCHAR2(250),
	MEMBER_TYPE           VARCHAR2(250),
	EFFECTIVE_START_DATE  DATE,
	EFFECTIVE_END_DATE    DATE,
	ATTRIBUTE1            NUMBER,
	ATTRIBUTE2            NUMBER,
	ATTRIBUTE3            NUMBER,
	ATTRIBUTE4            NUMBER,
	ATTRIBUTE5            NUMBER,
	ATTRIBUTE6            VARCHAR2(250),
	ATTRIBUTE7            VARCHAR2(250),
	ATTRIBUTE8            VARCHAR2(250),
	ATTRIBUTE9            VARCHAR2(250),
	ATTRIBUTE10           VARCHAR2(250),
	ATTRIBUTE11           VARCHAR2(250),
	ATTRIBUTE12           VARCHAR2(250),
	ATTRIBUTE13           VARCHAR2(250),
	ATTRIBUTE14           VARCHAR2(250),
	ATTRIBUTE15           VARCHAR2(250),
	CREATION_DATE         DATE,
	CREATED_BY            NUMBER,
	LAST_UPDATE_DATE      DATE,
	LAST_UPDATED_BY       NUMBER
);


ALTER TABLE ATET_SB_MEMBERS_BOARD
	ADD CONSTRAINT UQ_ATET_SB_MEMBERS_BOARD UNIQUE (MEMBER_BOARD_ID)
 USING INDEX ;


ALTER TABLE ATET_SB_MEMBERS_BOARD
    ADD CONSTRAINT FK_ATET_SB_MEMBERS_BOARD 
        FOREIGN KEY (SAVING_BANK_ID)
        REFERENCES ATET_SAVINGS_BANK(SAVING_BANK_ID); 


CREATE SEQUENCE ATET_SB_MEMBERS_BOARD_SEQ
  START WITH 10
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER ATET_SB_MEMBERS_BOARD_TGR
BEFORE INSERT
   ON ATET_SB_MEMBERS_BOARD
   FOR EACH ROW
DECLARE

   var_next_id  NUMBER;

BEGIN

    SELECT ATET_SB_MEMBERS_BOARD_SEQ.NEXTVAL
      INTO var_next_id
      FROM dual;        
      
    :NEW.MEMBER_BOARD_ID := var_next_id;

END;