CREATE TABLE ATET_SB_LOANS
(
	LOAN_ID               NUMBER    NOT NULL,
	MEMBER_ID             NUMBER    NOT NULL,
	LOAN_NUMBER           NUMBER,
	LOAN_TOTAL_AMOUNT     NUMBER,
	LOAN_AMOUNT           NUMBER,
	LOAN_INTEREST_AMOUNT  NUMBER,
    LOAN_INTEREST_RATE    NUMBER,
	TERM_PERIODS          NUMBER,
    NORMAL_INTEREST_RATE  NUMBER,
	LATE_INTEREST_RATE    NUMBER,
    TRANSACTION_DATE      DATE,
	PAYMENT_DEADLINE      DATE,
	PERIOD_TYPE           VARCHAR2(50),
	LOAN_STATUS_FLAG      VARCHAR2(15),
    LOAN_BALANCE          NUMBER,
    LAST_PAYMENT_DATE     DATE,
	ATTRIBUTE1            NUMBER,
	ATTRIBUTE2            NUMBER,
	ATTRIBUTE3            NUMBER,
	ATTRIBUTE4            NUMBER,
	ATTRIBUTE5            NUMBER,
	ATTRIBUTE6            VARCHAR2(250),
	ATTRIBUTE7            VARCHAR2(250),
	ATTRIBUTE8            VARCHAR2(250),
	ATTRIBUTE9            VARCHAR2(250),
	ATTRIBUTE10           VARCHAR2(250),
	ATTRIBUTE11           VARCHAR2(250),
	ATTRIBUTE12           VARCHAR2(250),
	ATTRIBUTE13           VARCHAR2(250),
	ATTRIBUTE14           VARCHAR2(250),
	ATTRIBUTE15           VARCHAR2(250),
	CREATION_DATE         DATE,
	CREATED_BY            NUMBER,
	LAST_UPDATE_DATE      DATE,
	LAST_UPDATED_BY       NUMBER
);


ALTER TABLE ATET_SB_LOANS
	ADD CONSTRAINT UQ_ATET_SB_LOANS UNIQUE (LOAN_ID)
 USING INDEX ;


ALTER TABLE ATET_SB_LOANS
    ADD CONSTRAINT FK_ATETSBLOANS_MEMBERID 
        FOREIGN KEY (MEMBER_ID)
        REFERENCES ATET_SB_MEMBERS(MEMBER_ID); 


CREATE SEQUENCE ATET_SB_LOANS_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE OR REPLACE TRIGGER ATET_SB_LOANS_TGR
BEFORE INSERT
   ON ATET_SB_LOANS
   FOR EACH ROW
DECLARE
    var_next_id  NUMBER;
BEGIN

    IF :NEW.LOAN_ID IS NULL THEN

        SELECT ATET_SB_LOANS_SEQ.NEXTVAL
          INTO var_next_id
          FROM dual;        
          
        :NEW.LOAN_ID := var_next_id;

    END IF;

END;