/**************************************************/
/*                  ALTER SESION                  */
/**************************************************/
ALTER SESSION SET CURRENT_SCHEMA=APPS; 


DELETE FROM ATET_SB_LOANS_TRANSACTIONS;
DELETE FROM ATET_SB_SAVINGS_TRANSACTIONS;
DELETE FROM ATET_SB_PAYMENTS_SCHEDULE;

DELETE FROM ATET_SB_PAYROLL_RESULTS WHERE ENTRY_NAME = 'Folio';



UPDATE ATET_SB_PAYROLL_RESULTS
   SET IMPORT_REQUEST_ID = NULL,
       ATTRIBUTE7 = NULL,
       ATTRIBUTE8 = NULL,
       ATTRIBUTE9 = NULL,
       ATTRIBUTE10 = NULL,
       ATTRIBUTE11 = NULL,
       ATTRIBUTE12 = NULL,
       ATTRIBUTE13 = NULL,
       ATTRIBUTE14 = NULL,
       ATTRIBUTE15 = NULL;




COMMIT;


SELECT *
  FROM ATET_SB_LOANS;
  
UPDATE ATET_SB_LOANS
   SET LOAN_STATUS_FLAG = 'APPROVED',
       LAST_PAYMENT_DATE = NULL,
       LOAN_BALANCE = LOAN_TOTAL_AMOUNT;
       
       
SELECT *
  FROM ATET_SB_MEMBERS_ACCOUNTS
 WHERE 1 = 1
   AND ACCOUNT_DESCRIPTION = 'D072_PRESTAMO CAJA DE AHORRO';
   
   
UPDATE ATET_SB_MEMBERS_ACCOUNTS
   SET CREDIT_BALANCE = 0,
       FINAL_BALANCE = DEBIT_BALANCE,
       LAST_TRANSACTION_DATE = NULL
 WHERE 1 = 1
   AND ACCOUNT_DESCRIPTION = 'D072_PRESTAMO CAJA DE AHORRO';
   
   
SELECT *
  FROM ATET_SB_MEMBERS_ACCOUNTS
 WHERE 1 = 1
   AND ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO';
   
   
UPDATE ATET_SB_MEMBERS_ACCOUNTS
   SET DEBIT_BALANCE = 0,
       CREDIT_BALANCE = 0,
       FINAL_BALANCE = 0,
       LAST_TRANSACTION_DATE = NULL
 WHERE 1 = 1
   AND ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO';
   
   
SELECT *
  FROM ATET_SB_LOANS_TRANSACTIONS;
   
SELECT *
  FROM ATET_SB_SAVINGS_TRANSACTIONS;
  
  
  
DROP SEQUENCE ATET_SB_SAVINGS_TRANS_SEQ;
CREATE SEQUENCE ATET_SB_SAVINGS_TRANS_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DROP SEQUENCE ATET_SB_PAYMENTS_SCHEDULE_SEQ;
CREATE SEQUENCE ATET_SB_PAYMENTS_SCHEDULE_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
DROP SEQUENCE ATET_SB_LOANS_TRAN_SEQ;
CREATE SEQUENCE ATET_SB_LOANS_TRAN_SEQ
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER;