PACKAGE BODY PAC_CUSTOMER_GOALS_PKG IS
  
  PROCEDURE ON_BTN_FIND_PRESSED
  IS
  BEGIN
  	SET_BLOCK_PROPERTY('PAC_CUSTOMER_GOALS',
									 DEFAULT_WHERE,
									 '    YEAR = NVL(''' || :CONTROL.YEAR || ''', YEAR) ' ||
									 'AND MONTH = NVL(''' || :CONTROL.MONTH || ''', MONTH) ' ||
									 'AND COUNTRY = NVL(''' || :CONTROL.COUNTRY || ''', COUNTRY) ' ||
									 'AND STATE = NVL(''' || :CONTROL.STATE || ''', STATE) ' ||
									 'AND CITY = NVL(''' || :CONTROL.CITY || ''', CITY) ' ||
									 'AND CLIENT_NAME = NVL(''' || :CONTROL.CLIENT_NAME || ''', CLIENT_NAME) ' ||
									 'AND ATTRIBUTE0 = ''Y''');
		GO_BLOCK('PAC_CUSTOMER_GOALS');
		EXECUTE_QUERY;
  END ON_BTN_FIND_PRESSED;
  
  PROCEDURE ON_BTN_RESTORE_PRESSED
  IS
  BEGIN
  
  	:CONTROL.YEAR := NULL;
  	:CONTROL.MONTH := NULL;
  	:CONTROL.COUNTRY := NULL;
  	:CONTROL.STATE := NULL;
  	:CONTROL.CITY := NULL;
  	:CONTROL.CLIENT_NAME := NULL;
  	
  	ON_BTN_FIND_PRESSED;  	
  
  END ON_BTN_RESTORE_PRESSED;
  
END;