SELECT PPF.PERIOD_TYPE,
       PPF.PAYROLL_NAME,
       PAPF.EMPLOYEE_NUMBER,
       PAPF.FULL_NAME,
       PAPF.LAST_NAME,
       PAPF.PER_INFORMATION1  AS "SECOND_LAST_NAME" , 
       (PAPF.FIRST_NAME 
        || ' ' || 
        PAPF.MIDDLE_NAMES)    AS "NAMES",
       PPTT.USER_PERSON_TYPE,
       PAPF.*
  FROM PAY_PAYROLLS_F           PPF,
       FND_LOOKUP_VALUES        FLV1,
       PER_ALL_PEOPLE_F         PAPF,             
       PER_ALL_ASSIGNMENTS_F    PAAF,
       PER_PERSON_TYPES_TL      PPTT 
 WHERE 1 = 1
   AND FLV1.LOOKUP_TYPE = 'NOMINAS POR EMPLEADOR LEGAL'
   AND FLV1.LOOKUP_CODE = :P_COMPANY_ID
   AND FLV1.LANGUAGE = USERENV('LANG')
   AND SUBSTR(PPF.PAYROLL_NAME,1,2) = FLV1.LOOKUP_CODE
   AND APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(PPF.PAYROLL_NAME) = NVL(:P_PERIOD_TYPE, APPS.PAC_HR_PAY_PKG.GET_PERIOD_TYPE(PPF.PAYROLL_NAME))
   AND PPF.PAYROLL_ID = NVL(:P_PAYROLL_ID, PPF.PAYROLL_ID)
   AND PAAF.PAYROLL_ID = PPF.PAYROLL_ID
   AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND PAAF.PERSON_ID = PAPF.PERSON_ID 
--   
   AND NVL(:P_YEAR, EXTRACT(YEAR FROM SYSDATE)) BETWEEN EXTRACT(YEAR FROM PAPF.EFFECTIVE_START_DATE) AND EXTRACT(YEAR FROM PAPF.EFFECTIVE_END_DATE)
   AND PPTT.PERSON_TYPE_ID = PAPF.PERSON_TYPE_ID
   AND PPTT.LANGUAGE = USERENV('LANG')
   AND PPTT.USER_PERSON_TYPE = NVL(:P_PERSON_TYPE, PPTT.USER_PERSON_TYPE)
   
     
   