CREATE TABLE PAC_VALUESET_VALUES_TB(
    FLEX_VALUE_SET_ID       NUMBER,
    FLEX_VALUE_SET_NAME     VARCHAR2(60),
    FLEX_VALUE_ID           NUMBER,
    FLEX_VALUE              VARCHAR2(150),
    ENABLED_FLAG            VARCHAR2(1),   
    START_DATE_ACTIVE       DATE,
    END_DATE_ACTIVE         DATE,
    DESCRIPTION             VARCHAR2(240)
);