SELECT ASM.EMPLOYEE_NUMBER,
       ASM.EMPLOYEE_FULL_NAME,
       ASM.EMPLOYEE_NUMBER,
       ASM.MEMBER_ID
  FROM ATET_SB_MEMBERS  ASM
 WHERE 1 = 1;
 
 
SELECT CONCAT(CONCAT(ASM.EMPLOYEE_NUMBER, 
                     ASM.MEMBER_ID), 
              ASL.LOAN_NUMBER)          AS KEY,
       ASM.EMPLOYEE_NUMBER,
       ASM.EMPLOYEE_FULL_NAME,
       ASL.MEMBER_ID,
       ASL.LOAN_ID,
       ASL.LOAN_NUMBER,
       ASL.LOAN_BALANCE,
       ASL.ATTRIBUTE3,
       ASL.LOAN_ID,
       ASL.LOAN_NUMBER,
       ASL.LOAN_BALANCE,
       ASL.LOAN_AMOUNT
  FROM ATET_SB_LOANS    ASL,
       ATET_SB_MEMBERS  ASM
 WHERE 1 = 1
   AND ASL.MEMBER_ID = ASM.MEMBER_ID;
   
   
SELECT ASM.EMPLOYEE_NUMBER,
       ASM.EMPLOYEE_FULL_NAME,
       ASMA.MEMBER_ACCOUNT_ID,
       ASMA.FINAL_BALANCE
  FROM ATET_SB_MEMBERS          ASM,
       ATET_SB_MEMBERS_ACCOUNTS ASMA
 WHERE 1 = 1
   AND ASM.MEMBER_ID = ASMA.MEMBER_ID
   AND ASMA.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
   
   
   
  