ALTER SESSION SET CURRENT_SCHEMA = APPS;

SELECT *
  FROM ATET_XLA_HEADERS
 ORDER BY ACCOUNTING_DATE DESC;
 
 
 
SELECT SUM(ACCOUNTED_DR),
       SUM(ACCOUNTED_CR)
  FROM ATET_XLA_LINES
 WHERE 1 = 1
   AND HEADER_ID = 6560; 
   
   
SELECT SUM(ENTERED_DR),
       SUM(ENTERED_CR),
       SUM(ACCOUNTED_DR),
       SUM(ACCOUNTED_CR)
  FROM GL_INTERFACE
 WHERE 1 = 1
   AND LEDGER_ID = 2084;
   
SELECT DISTINCT STATUS
FROM GL_INTERFACE
WHERE 1 = 1
AND LEDGER_ID = 2084; 
   
UPDATE GL_INTERFACE
   SET STATUS = 'NEW'
 WHERE STATUS IN ('EU02,P', 'EU02,EC12')
   AND LEDGER_ID = 2084;
   
COMMIT;   
   

ROLLBACK;
   
  