CREATE OR REPLACE VIEW ATET_SB_CALENDAR_WEEK
AS
SELECT DISTINCT
       D.PERIOD_NUM                     AS  "PERIOD_NUM",
       D.PERIOD_NAME                    AS  "PERIOD_NAME",
       SUBSTR(ASPR.ATTRIBUTE6,1,1)      AS  "EXPORTED_FLAG",
       SUBSTR(ASST.TRANSACTION_CODE,1,1)AS  "PROCESSED_FLAG",
       SUBSTR(ASST.ACCOUNTED_FLAG,1,1)  AS  "ACCOUNTED_FLAG"
  FROM (SELECT DISTINCT
               PTP.PERIOD_NUM,
               PTP.PERIOD_NAME
          FROM PER_TIME_PERIODS             PTP,
               ATET_SAVINGS_BANK            ASB
         WHERE 1 = 1
           AND ASB.SAVING_BANK_ID = ATET_SAVINGS_BANK_PKG.GET_SAVING_BANK_ID
           AND EXTRACT(YEAR FROM PTP.END_DATE) = ASB.YEAR
           AND PTP.PERIOD_TYPE IN ('Semana', 'Week')
           AND PTP.END_DATE BETWEEN ASB.OPENING_DATE AND ASB.TERMINATION_DATE) D
  LEFT JOIN ATET_SB_PAYROLL_RESULTS         ASPR  
    ON D.PERIOD_NAME = ASPR.PERIOD_NAME
  LEFT JOIN ATET_SB_SAVINGS_TRANSACTIONS    ASST
    ON D.PERIOD_NAME = ASST.PERIOD_NAME
 ORDER BY D.PERIOD_NUM;
