SELECT ASMA.MEMBER_ID,
       ASMA.MEMBER_ACCOUNT_ID,
       ASMA.ACCOUNT_DESCRIPTION,
       (ASST.DEBIT_AMOUNT)       AS  DEBIT_AMOUNT
  FROM ATET_SB_MEMBERS_ACCOUNTS     ASMA,
       ATET_SB_SAVINGS_TRANSACTIONS ASST
 WHERE 1 = 1
   AND ASMA.MEMBER_ID = :P_MEMBER_ID
   AND ASMA.MEMBER_ACCOUNT_ID = ASST.MEMBER_ACCOUNT_ID
   AND ASMA.MEMBER_ID = ASST.MEMBER_ID
   AND ASMA.ACCOUNT_DESCRIPTION IN ('D071_CAJA DE AHORRO', 'INTERES GANADO')
   AND ASST.ATTRIBUTE7 = 'REPARTO DE AHORRO'
-- GROUP BY ASMA.MEMBER_ID,
--          ASMA.MEMBER_ACCOUNT_ID,
--          ASMA.ACCOUNT_DESCRIPTION
 ORDER BY ASMA.ACCOUNT_DESCRIPTION