SELECT ASM.EMPLOYEE_NUMBER,
       ASM.EMPLOYEE_FULL_NAME,
       ASM.MEMBER_ID       
  FROM ATET_SB_MEMBERS          ASM, ATET_SB_MEMBERS_ACCOUNTS ASMA_SAV, ATET_SB_MEMBERS_ACCOUNTS ASMA_INT, ATET_SAVINGS_BANK        ASB
 WHERE 1 = 1
   AND ASM.MEMBER_ID = ASMA_SAV.MEMBER_ID
   AND ASM.MEMBER_ID = ASMA_INT.MEMBER_ID
   AND ASMA_SAV.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
   AND ASMA_INT.ACCOUNT_DESCRIPTION = 'INTERES GANADO'
   AND ASMA_SAV.FINAL_BALANCE = 0
   AND ASMA_INT.FINAL_BALANCE = 0
   AND ASM.SAVING_BANK_ID = ASB.SAVING_BANK_ID
   AND ASB.YEAR = :P_YEAR