SELECT 'ASOCIACION DE TRABAJADORES Y EMPLEADOS DE TEHUACAN, S.C.'   AS  COMPANY_NAME,
       ASM.EMPLOYEE_NUMBER                                          AS  EMPLOYEE_NUMBER,
       ASM.EMPLOYEE_FULL_NAME                                       AS  EMPLOYEE_FULL_NAME,
       ASM.PERSON_ID                                                AS  PERSON_ID,
       PAPF.NATIONAL_IDENTIFIER                                     AS  CURP,
       PAPF.PER_INFORMATION2                                        AS  RFC,
       PPF.PAYROLL_NAME                                             AS  PAYROLL_NAME,
       HOU.NAME                                                     AS  DEPARTMENT_NAME,
       HAP.NAME                                                     AS  JOB_NAME
  FROM ATET_SB_MEMBERS          ASM,
       ATET_SB_MEMBERS_ACCOUNTS ASMA_SAV,
       ATET_SB_MEMBERS_ACCOUNTS ASMA_INT,
       PER_ALL_PEOPLE_F         PAPF,
       PER_ALL_ASSIGNMENTS_F    PAAF,
       PAY_PAYROLLS_F           PPF,
       HR_ORGANIZATION_UNITS    HOU,
       HR_ALL_POSITIONS_F       HAP,
 WHERE 1 = 1
   AND ASM.MEMBER_ID = ASMA_SAV.MEMBER_ID
   AND ASM.MEMBER_ID = ASMA_INT.MEMBER_ID
   AND ASMA_SAV.ACCOUNT_DESCRIPTION = 'D071_CAJA DE AHORRO'
   AND ASMA_INT.ACCOUNT_DESCRIPTION = 'INTERES GANADO'
   AND ASMA_SAV.FINAL_BALANCE = 0
   AND ASMA_INT.FINAL_BALANCE = 0
   AND PAPF.PERSON_ID = ASM.PERSON_ID
   AND PAAF.PERSON_ID = ASM.PERSON_ID
   AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
   AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
   AND PAAF.PAYROLL_ID = PPF.PAYROLL_ID
   AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
   AND HOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
   AND SYSDATE BETWEEN HOU.
   AND HAP.POSITION_ID = PAAF.POSITION_ID;
   
   
  