LOAD DATA
BADFILE '/PAC_UPDATE_ACCOUNT_EDENRED.BAD'
DISCARDFILE '/PAC_UPDATE_ACCOUNT_EDENRED.DSC'
REPLACE
INTO TABLE APPS.PAC_UPDATE_ACCOUNT_EDENRED_TB
Fields terminated by "," Optionally enclosed by '"'
(
  EMPLOYEE_NUMBER,
  ACCOUNT_NUMBER,
  CARD_NUMBER
)

