CREATE OR REPLACE PACKAGE PAC_VERIFY_CEDIS_PKG  AS
    
    FUNCTION VERIFY_STEP1 (COLUMN_DESC    VARCHAR2, COLUMN_VAL     VARCHAR2) RETURN VARCHAR2;
    FUNCTION VERIFY_STEP2 (COLUMN_DESC    VARCHAR2, COLUMN_VAL     VARCHAR2, P_ORG_INVENTORY_ID  NUMBER   DEFAULT 0)                                            RETURN VARCHAR2;
    FUNCTION VERIFY_STEP4 (COLUMN_DESC    VARCHAR2, COLUMN_VAL     VARCHAR2, P_ORG_INVENTORY_ID  NUMBER   DEFAULT 0, P_OPERATING_UNIT_ID NUMBER   DEFAULT 0)    RETURN VARCHAR2;
    FUNCTION VERIFY_STEP5 (ORGANIZATION_CODE VARCHAR2, RESPONSABILITY_NAME  VARCHAR2)   RETURN VARCHAR2;
    FUNCTION VERIFY_STEP6 (COLUMN_DESC    VARCHAR2, COLUMN_VAL     VARCHAR2) RETURN VARCHAR2;
    
    
    FUNCTION GET_OPERATING_UNIT(P_OPERATING_UNIT_ID  NUMBER)    RETURN VARCHAR2;
    FUNCTION GET_ORG_INVENTORY(P_ORG_INVENTORY_ID  NUMBER)      RETURN VARCHAR2;
    FUNCTION GET_ACCOUNT(P_CODE_COMBINATION_ID  NUMBER)         RETURN VARCHAR2;
    FUNCTION GET_ORGANIZATION_CODE(P_ORG_INVENTORY_ID   NUMBER) RETURN VARCHAR2;
    FUNCTION GET_LOCATION_CODE(P_ORG_INVENTORY_ID  NUMBER)      RETURN VARCHAR2;
    FUNCTION GET_ID_UOSTO(P_OPERATING_UNIT_ID   NUMBER)         RETURN VARCHAR2;

END PAC_VERIFY_CEDIS_PKG;