SELECT /*+ LEADING(PAPF, PAAF, PPF, PPA, PTP, PPG, HAPF, PPD, HOU, PAA, PRR, PRRV) */ 
       PAPF.PERSON_ID,
       PAAF.ASSIGNMENT_ID,
       PPF.PAYROLL_ID,
       PPA.PAYROLL_ACTION_ID,
       PTP.TIME_PERIOD_ID,
       PAA.ASSIGNMENT_ACTION_ID,
       PRR.RUN_RESULT_ID,
       PRRV.RESULT_VALUE
  FROM PER_ALL_PEOPLE_F             PAPF,
       PER_ALL_ASSIGNMENTS_F        PAAF,
       PAY_ALL_PAYROLLS_F           PPF,
       PAY_PAYROLL_ACTIONS          PPA,
       PER_TIME_PERIODS             PTP,
       PAY_ASSIGNMENT_ACTIONS       PAA,
       PAY_RUN_RESULTS              PRR,
       PAY_RUN_RESULT_VALUES        PRRV
 WHERE 1 = 1
   AND PAPF.PERSON_ID = PAAF.PERSON_ID
   AND PPF.PAYROLL_ID = PAAF.PAYROLL_ID
   AND PPA.PAYROLL_ID = PPF.PAYROLL_ID
   AND PTP.PAYROLL_ID = PPF.PAYROLL_ID
   AND PPA.TIME_PERIOD_ID = PTP.TIME_PERIOD_ID
   AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
   AND PAA.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
   AND PRR.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID
   AND PRRV.RUN_RESULT_ID = PRR.RUN_RESULT_ID
   AND PPA.EFFECTIVE_DATE BETWEEN PAPF.EFFECTIVE_START_DATE
                              AND PAPF.EFFECTIVE_END_DATE
   AND PPA.EFFECTIVE_DATE BETWEEN PAAF.EFFECTIVE_START_DATE
                              AND PAAF.EFFECTIVE_END_DATE
   AND PPA.EFFECTIVE_DATE BETWEEN PPF.EFFECTIVE_START_DATE
                              AND PPF.EFFECTIVE_END_DATE
   