ALTER SESSION SET CURRENT_SCHEMA=APPS;



SELECT PPA.PAYROLL_ACTION_ID
      ,PPA.ASSIGNMENT_SET_ID
      ,PTP.TIME_PERIOD_ID
      ,PTP.END_DATE
      ,PAA.ASSIGNMENT_ACTION_ID
      ,PAAF.PERSON_ID
      ,PAAF.ASSIGNMENT_NUMBER
      ,PRR.RUN_RESULT_ID
      ,PETF.ELEMENT_TYPE_ID
      ,PETF.ELEMENT_NAME
      ,PETF.ATTRIBUTE1                          CLASIFICACION_PAC
      ,NVL (DECODE (PC.DEBIT_OR_CREDIT,
                    'D', PC.COSTED_VALUE,
                    NULL), 0)                   DEBIT_AMOUNT
      ,PC.COST_ALLOCATION_KEYFLEX_ID 
      ,HAOU.ATTRIBUTE7                          CC
      ,HAOU.ATTRIBUTE3                          MANO_DE_OBRA 
      ,HAOU.ATTRIBUTE4                          CARGA_SOCIAL
      ,HAOU.ATTRIBUTE5                          BONOS
      ,HAOU.ATTRIBUTE6                          FONDO_DE_AHORRO
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'CONCATENATED_SEGMENTS')           SEG
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT1')                        SEGMENT1
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT2')                        SEGMENT2
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT3')                        SEGMENT3
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT4')                        SEGGMENT4
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT5')                        SEGMENT5
      ,XXCALV_PAY_POLIZA_PKG.
        GET_CONCATENED_SEGMENTS
            (PC.COST_ALLOCATION_KEYFLEX_ID
            ,'SEGMENT6')                        SEGMENT6
  FROM PAY_PAYROLL_ACTIONS              PPA
      ,PAY_ALL_PAYROLLS_F               PAPF 
      ,PER_TIME_PERIODS                 PTP
      ,PAY_ASSIGNMENT_ACTIONS           PAA
      ,PER_ALL_ASSIGNMENTS_F            PAAF
      ,PAY_RUN_RESULTS                  PRR 
      ,PAY_ELEMENT_TYPES_F              PETF
      ,PAY_COSTS                        PC
      ,HR_ALL_ORGANIZATION_UNITS        HAOU
 WHERE 1 = 1
   AND PPA.PAYROLL_ID = NVL(:P_PAYROLL_ID, PPA.PAYROLL_ID) 
   AND NVL(PPA.CONSOLIDATION_SET_ID, 0) = NVL(:P_CONSOLIDATION_ID, NVL(PPA.CONSOLIDATION_SET_ID, 0))
   AND NVL(PPA.ASSIGNMENT_SET_ID, 0) = NVL(:P_ASSIGNMENT_SET_ID, NVL(PPA.ASSIGNMENT_SET_ID, 0))
   AND PPA.EFFECTIVE_DATE BETWEEN NVL(:PP_START_DATE,PPA.EFFECTIVE_DATE) 
                              AND :PP_END_DATE
   AND PPA.ACTION_TYPE IN ('R', 'Q')
   AND PAPF.PAYROLL_ID = PPA.PAYROLL_ID
   AND PAPF.PERIOD_TYPE = :P_PERIOD_TYPE
   AND PTP.TIME_PERIOD_ID = PPA.TIME_PERIOD_ID
   AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
   AND PAA.ACTION_STATUS = 'C'
   AND PAAF.ASSIGNMENT_ID = PAA.ASSIGNMENT_ID
   AND PPA.EFFECTIVE_DATE  BETWEEN PAAF.EFFECTIVE_START_DATE AND 
                                   PAAF.EFFECTIVE_END_DATE
   AND PAAF.ASS_ATTRIBUTE15 = 'PAC'  
   AND PRR.ASSIGNMENT_ACTION_ID = PAA.ASSIGNMENT_ACTION_ID
   AND PETF.ELEMENT_TYPE_ID = PRR.ELEMENT_TYPE_ID 
   AND PETF.ATTRIBUTE1 IS NOT NULL     
   AND PETF.ATTRIBUTE1 != 'N/A'
   AND PC.RUN_RESULT_ID = PRR.RUN_RESULT_ID
   AND NVL (DECODE (PC.DEBIT_OR_CREDIT,
                    'D', PC.COSTED_VALUE,
                    NULL), 0) <> 0
   AND PC.DEBIT_OR_CREDIT = 'D'
   AND HAOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
   AND HAOU.ATTRIBUTE7 IS NOT NULL 
 ORDER BY HAOU.ATTRIBUTE7, PAAF.ASSIGNMENT_NUMBER, PETF.ELEMENT_NAME
; -- FIN



