LOAD DATA
BADFILE '/PAC_ASSET_ADDITIONS.BAD'
DISCARDFILE '/PAC_ASSET_ADDITIONS.DSC'
REPLACE
INTO TABLE APPS.PAC_ASSET_ADDITIONS_TB
Fields terminated by "," Optionally enclosed by '"'
(
  	DESCRIPTION,
	TAG_NUMBER,
	SERIAL_NUMBER,
	UNITS,
	CATEGORY,
	COST,
	VENDOR_NAME,
	INVOICE_NUMBER,
	BOOK_CODE,
	DATE_IN_SERVICE,
	DEPRECIATE_METHOD,
	PRORATE_CODE,
	CODE_COMBINATION,
	LOCATION
)

