SELECT 
       PAPF.FULL_NAME,
       PPPM.PERSONAL_PAYMENT_METHOD_ID,
       PPPM.OBJECT_VERSION_NUMBER,
       PPPM.EXTERNAL_ACCOUNT_ID,
       PPPM.ATTRIBUTE1,
       PEA.SEGMENT3
  FROM PER_ALL_PEOPLE_F                 PAPF,
       PER_ALL_ASSIGNMENTS_F            PAAF,
       PAY_PERSONAL_PAYMENT_METHODS_F   PPPM,
       PAY_ORG_PAYMENT_METHODS_F        POPM,
       PAY_EXTERNAL_ACCOUNTS            PEA
 WHERE 1 = 1
   AND PAPF.EMPLOYEE_NUMBER = :p_employee_number
   AND PAPF.PERSON_ID = PAAF.PERSON_ID
   AND PPPM.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID
   AND PPPM.ORG_PAYMENT_METHOD_ID = POPM.ORG_PAYMENT_METHOD_ID
   AND POPM.ORG_PAYMENT_METHOD_NAME LIKE '%-EDENRED DESPENSA'
   AND PEA.EXTERNAL_ACCOUNT_ID = PPPM.EXTERNAL_ACCOUNT_ID
   AND PPPM.OBJECT_VERSION_NUMBER = (SELECT 
                                        MAX(PM.OBJECT_VERSION_NUMBER)
                                       FROM PAY_PERSONAL_PAYMENT_METHODS_F PM
                                      WHERE PM.ASSIGNMENT_ID = PAAF.ASSIGNMENT_ID)
   AND PEA.OBJECT_VERSION_NUMBER = (SELECT
                                       MAX(EA.OBJECT_VERSION_NUMBER)
                                      FROM PAY_EXTERNAL_ACCOUNTS    EA
                                     WHERE EA.EXTERNAL_ACCOUNT_ID = PEA.EXTERNAL_ACCOUNT_ID)
