CREATE OR REPLACE PACKAGE PAC_FINANCING_DEDUCTIONS_FUNCTIONS_PKG AS

    FUNCTION GET_WEEK_NUMBER(P_DATE_EARNED DATE) 
    RETURN NUMBER;
    
    FUNCTION HAS_EMPLOYMENT_SUBSIDY(P_ASSIGNMENT_ID NUMBER, P_DATE_EARNED DATE)
    RETURN NUMBER;    
    
    FUNCTION AVERAGE_EMPLOYMENT_SUBSIDY(P_ASSIGNMENT_ID NUMBER, P_DATE_EARNED DATE)
    RETURN NUMBER;
    
    FUNCTION AVERAGE_EMPLOYMENT_TAX(P_ASSIGNMENT_ID NUMBER, P_DATE_EARNED DATE)
    RETURN NUMBER;

END PAC_D055_ISPT_FUNCTIONS_PKG;
