SELECT DISTINCT
       PFEE.VEHICLE_ID,          
       PFEE.VEHICLE                 AS  "VEHICLE", 
       PFED.DEPARTURE_DATE          AS  "DEPARTURE_DATE",
       PFEE.TRAFFIC_NUMBER          AS  "TRAFFIC_NUMBER",
       PFEE.ATTRIBUTE5              AS  "DRIVER_NAME",
       PFEE.ATTRIBUTE1              AS  "DESTINATION_NAME",
       PFEE.ATTRIBUTE6              AS  "TRAILER_TYPE",
       PFEE.ATTRIBUTE7              AS  "BOX_NUMBER",
       PFEE.EXPECTED_EFFICIENCY     AS  "EXPECTED_EFFICIENCY",
       PFEE.LAST_READING            AS  "LAST_READING",
       PFEE.ACTUAL_READING          AS  "ACTUAL_READING",
       PFEE.TRIP_DISTANCE           AS  "TRIP_DISTANCE",
       PFEE.CONSUMED_FUEL           AS  "CONSUMED_FUEL",
       PFEE.EXTERNAL_CONSUMED_FUEL  AS  "EXTERNAL_CONSUMED_FUEL",
       PFEE.TOTAL_CONSUMED_FUEL     AS  "TOTAL_CONSUMED_FUEL",
       PFEE.REAL_EFFICIENCY         AS  "REAL_EFFICIENCY",
       NVL(PFEE.ATTRIBUTE3, 0)      AS  "CONSUMED_DIFFERENCE",
       TRUNC((NVL(PFEE.ATTRIBUTE3, 0) * :P_FUEL_RATE), 2) AS "TOTAL"  
  FROM PAC_FUEL_EC_EFFICIENCIES   PFEE,
       PAC_FUEL_EC_DEPARTURES     PFED
 WHERE 1 = 1
   AND PFEE.DEPARTURE_ID = PFED.DEPARTURE_ID
   AND PFED.DEPARTURE_TYPE = 'SALIDA'
   AND PFEE.ATTRIBUTE4 = 'Y'
   AND PFED.DEPARTURE_DATE BETWEEN :CP_START_DATE AND :CP_END_DATE
   AND PFEE.VEHICLE_ID = NVL(:P_VEHICLE_ID, PFEE.VEHICLE_ID)
 ORDER BY TO_DATE(PFED.DEPARTURE_DATE),
          PFEE.VEHICLE,
          PFEE.TRAFFIC_NUMBER