CREATE OR REPLACE PACKAGE APPS.CONFIGURATION_CEDIS_PKG IS

    PROCEDURE   SET_PARAMETER
                (
                    P_API_NAME          CONFIGURATION_CEDIS_TB.API_NAME%TYPE,
                    P_PARAMETER_NAME    CONFIGURATION_CEDIS_TB.PARAMETER_NAME%TYPE,
                    P_PARAMETER_VALUE   CONFIGURATION_CEDIS_TB.PARAMETER_VALUE%TYPE
                );
                
    PROCEDURE   SET_RESULT
                (
                    P_API_NAME          CONFIGURATION_CEDIS_TB.API_NAME%TYPE,
                    P_RESULT_NAME       CONFIGURATION_CEDIS_TB.RESULT_NAME%TYPE,
                    P_RESULT_VALUE      CONFIGURATION_CEDIS_TB.RESULT_VALUE%TYPE
                );
                
    PROCEDURE   INITIALIZE_CEDIS
                (
                    P_OU_NAME               CONFIGURATION_CEDIS_TB.OU_NAME%TYPE,
                    P_LOCATION_CODE         CONFIGURATION_CEDIS_TB.PARAMETER_VALUE%TYPE,
                    P_DESCRIPTION           CONFIGURATION_CEDIS_TB.PARAMETER_VALUE%TYPE
                );
    
    PROCEDURE   FINALIZE_CEDIS;
    
    FUNCTION    GET_OU_NAME
      RETURN    CONFIGURATION_CEDIS_TB.OU_NAME%TYPE;
      
    FUNCTION    GET_PARAMETER_VALUE
                (
                    P_API_NAME          CONFIGURATION_CEDIS_TB.API_NAME%TYPE,
                    P_PARAMETER_NAME    CONFIGURATION_CEDIS_TB.PARAMETER_NAME%TYPE
                )
      RETURN    CONFIGURATION_CEDIS_TB.PARAMETER_VALUE%TYPE;
      
    FUNCTION    GET_RESULT_VALUE
                (
                    P_API_NAME          CONFIGURATION_CEDIS_TB.API_NAME%TYPE,
                    P_RESULT_NAME       CONFIGURATION_CEDIS_TB.RESULT_NAME%TYPE
                )
      RETURN    CONFIGURATION_CEDIS_TB.RESULT_VALUE%TYPE;     

END CONFIGURATION_CEDIS_PKG;