CREATE OR REPLACE VIEW GL_DOC_SEQUENCE_VALUE_V(
                       DOC_SEQUENCE_VALUE,
                       USER_JE_CATEGORY_NAME,
                       USER_JE_SOURCE_NAME)
AS
SELECT DISTINCT
       GJH.DOC_SEQUENCE_VALUE,
       GLC.USER_JE_CATEGORY_NAME,
       GLS.USER_JE_SOURCE_NAME
  FROM GL_JE_HEADERS       GJH, 
       GL_JE_CATEGORIES_TL GLC, 
       GL_JE_SOURCES_TL    GLS
 WHERE GJH.JE_CATEGORY = GLC.JE_CATEGORY_NAME 
   AND   GJH.JE_SOURCE = GLS.JE_SOURCE_NAME 
   AND   GJH.DOC_SEQUENCE_VALUE IS NOT NULL
--AND   GLC.USER_JE_CATEGORY_NAME = :XXCALVL_CATEGORIA
--AND   GLS.USER_JE_SOURCE_NAME   = :XXCALVL_ORIGEN
   AND GLC.LANGUAGE = 'ESA'
   AND GLS.LANGUAGE = 'ESA'
 ORDER BY  GJH.DOC_SEQUENCE_VALUE;