 
DEFAULT FOR ASG_STATUS                     IS 'Active Assignment'
DEFAULT FOR PER_EMP_NUMBER                 IS  '0'

Flag_Emp_Ajuste_Anual = 'S'

IF (PER_EMP_NUMBER = '50' OR  /*LOPEZ ALVAREZ ANA*/
    PER_EMP_NUMBER = '41' OR  /*ROMERO VALERIO FELIPE*/
    PER_EMP_NUMBER = '45' OR  /*PACHECO CID MARIA DEL CARMEN*/
    PER_EMP_NUMBER = '70' OR  /*CORTES VEGA MARIA DEL ROCIO*/
    PER_EMP_NUMBER = '75' OR  /*VEGA PASTRANA JORGE ANTONIO*/
    PER_EMP_NUMBER = '74' OR  /*MORAN VELEZ ELBA*/
    PER_EMP_NUMBER = '82' OR  /*TLAQUIZ SORIANO CLAUDIA ISELA*/
    PER_EMP_NUMBER = '77' OR  /*GARCIA CORTES ROSA MARIA*/
    PER_EMP_NUMBER = '3980')  /*ARANDIA GARCIA DE LA CADENA CARLOS*/
THEN (Flag_Emp_Ajuste_Anual = 'N')

IF (ASG_STATUS LIKE 'Asignación Activa' OR ASG_STATUS LIKE 'Active Assignment') AND 
      Flag_Emp_Ajuste_Anual = 'S'     AND 
      IS_ASG_EXEMPT_FROM_ISR () = 'N' AND 
      CHECK_EE_EMPLOYMENT_CRITERIA () = 'Y'
THEN
   ( 
    INCLUDE_FLAG ='Y' 
   )
ELSE
     (
       INCLUDE_FLAG = 'N'
     )  

RETURN INCLUDE_FLAG