CREATE OR REPLACE PACKAGE APPS.TIMECLOCK_PKG IS


    /* 
    CREATE A LIST OF DATES IN TIMECLOCK_DATES_TB
    BETWEEN @PARAM P_START_DATE
    AND     @PARAM P_END_DATE
    */
    PROCEDURE TIMECLOCK_ADD_DAYS_PRC(
                P_START_DATE    VARCHAR2, 
                P_END_DATE      VARCHAR2);
    
    
    /* 
    CHECK THE DELAY AMONG THE CHECK HOUR
    */
    FUNCTION  TIMECLOCK_HAS_DELAY(
                P_CHECK_DAY     TIMESTAMP)
    RETURN VARCHAR2;
    
    
    /* 
    APPLY THE FORMAT HOUR HH12:MI:SS AM TO CHECK DAY
    */
    FUNCTION  TIMECLOCK_FORMAT_HOUR(
                P_CHECK_DAY     TIMESTAMP)
    RETURN VARCHAR2;    
    
    
    /*
    GET ABSENCE DESC OR DESABILITY DESC FROM
        PER_ABSENCE_ATTENDANCES_V
        PER_DISABILITIES_F
    BY  @PARAM P_PERSON_ID
    AND @PARAM P_CHECK_DATE
    */
    FUNCTION  TIMECLOCK_ABSENCE_DESC(
                P_PERSON_ID         NUMBER,
                P_CHECK_DATE        DATE)
    RETURN VARCHAR2;    
    
    FUNCTION  GET_BONUS(
                P_PERSON_ID         NUMBER,
                P_START_DATE        DATE,
                P_END_DATE          DATE)
    RETURN VARCHAR2;                        

END TIMECLOCK_PKG;
/
