        SELECT PTP.PERIOD_NAME,
               PAA.*,
               PPA.*
--          INTO var_count_periods
          FROM ATET_SB_MEMBERS          ASM,
               ATET_SAVINGS_BANK        ASB,
               PER_ASSIGNMENTS_F        PAF,
               PER_TIME_PERIODS         PTP,
               PAY_ASSIGNMENT_ACTIONS   PAA,
               PAY_PAYROLL_ACTIONS      PPA
         WHERE 1 = 1
           AND ASM.PERSON_ID = PAF.PERSON_ID
           AND ASM.SAVING_BANK_ID = ASB.SAVING_BANK_ID
           AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
           AND ASM.MEMBER_ID = :P_MEMBER_ID
           AND PTP.PAYROLL_ID = PAF.PAYROLL_ID
           AND PAA.ASSIGNMENT_ID = PAF.ASSIGNMENT_ID
           AND PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
           AND PAF.PAYROLL_ID = PPA.PAYROLL_ID
           AND PTP.TIME_PERIOD_ID = PPA.TIME_PERIOD_ID
           AND PAA.RUN_TYPE_ID IS NOT NULL
           AND EXTRACT(YEAR FROM PTP.END_DATE) = ASB.YEAR
           AND PTP.END_DATE BETWEEN SYSDATE AND ASB.TERMINATION_DATE;