SELECT ASM.PERSON_ID,
       ASM.EMPLOYEE_FULL_NAME,
       ASMA.ACCOUNT_DESCRIPTION,
       ASMA.DEBIT_BALANCE,
       ASMA.CREDIT_BALANCE,
       ASMA.FINAL_BALANCE,
       SUM(ASST.ENTRY_VALUE)    AS  ENTRY_VALUE,
       SUM(ASST.DEBIT_AMOUNT)   AS  DEBIT_AMOUNT,
       SUM(ASST.CREDIT_AMOUNT)  AS  CREDIT_AMOUNT
  FROM ATET_SB_MEMBERS              ASM,
       ATET_SB_MEMBERS_ACCOUNTS     ASMA,
       ATET_SB_SAVINGS_TRANSACTIONS ASST
 WHERE 1 = 1
   AND ASM.MEMBER_ID = ASMA.MEMBER_ID
   AND ASM.MEMBER_ID = ASST.MEMBER_ID
   AND ASMA.MEMBER_ACCOUNT_ID = ASST.MEMBER_ACCOUNT_ID
 GROUP BY ASM.PERSON_ID,
       ASM.EMPLOYEE_FULL_NAME,
       ASMA.ACCOUNT_DESCRIPTION,
       ASMA.DEBIT_BALANCE,
       ASMA.CREDIT_BALANCE,
       ASMA.FINAL_BALANCE