SELECT COUNT(D.PERIOD_NAME)
--       D.PERIOD_NAME,
--       D.TIME_PERIOD_ID,
--       D.ASSIGNMENT_ID,
--       D.PAYROLL_ID,
--       D.END_DATE,
--       PPA.TIME_PERIOD_ID,
--       PAA.RUN_TYPE_ID
  FROM (SELECT PTP.PERIOD_NAME,
               PTP.TIME_PERIOD_ID,
               PAF.ASSIGNMENT_ID,
               PAF.PAYROLL_ID,
               PTP.START_DATE,
               PTP.END_DATE,
               PAF.EFFECTIVE_START_DATE,
               PAF.EFFECTIVE_END_DATE
          FROM ATET_SB_MEMBERS          ASM,
               ATET_SAVINGS_BANK        ASB,
               PER_ASSIGNMENTS_F        PAF,
               PER_TIME_PERIODS         PTP
         WHERE 1 = 1
           AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
           AND ASM.PERSON_ID = PAF.PERSON_ID
           AND ASM.SAVING_BANK_ID = ASB.SAVING_BANK_ID
           AND ASM.MEMBER_ID = :P_MEMBER_ID
           AND PTP.PAYROLL_ID = PAF.PAYROLL_ID    
           AND EXTRACT(YEAR FROM PTP.END_DATE) = ASB.YEAR
           AND PTP.END_DATE BETWEEN SYSDATE AND ASB.TERMINATION_DATE) D
   LEFT JOIN PAY_PAYROLL_ACTIONS          PPA
     ON PPA.PAYROLL_ID = D.PAYROLL_ID
    AND PPA.TIME_PERIOD_ID = D.TIME_PERIOD_ID
    AND PPA.EFFECTIVE_DATE BETWEEN D.START_DATE AND D.END_DATE
    AND PPA.EFFECTIVE_DATE BETWEEN D.EFFECTIVE_START_DATE AND D.EFFECTIVE_END_DATE
   LEFT JOIN PAY_ASSIGNMENT_ACTIONS       PAA
     ON PAA.PAYROLL_ACTION_ID = PPA.PAYROLL_ACTION_ID
    AND PAA.ASSIGNMENT_ID = D.ASSIGNMENT_ID
    AND PAA.RUN_TYPE_ID IS NOT NULL 
  WHERE 1 = 1 
    AND PPA.TIME_PERIOD_ID IS NULL
  ORDER BY D.TIME_PERIOD_ID
