DECLARE
    CURSOR DETAIL_LIST IS
        SELECT PERSON_ID
          FROM ATET_SB_MEMBERS;
BEGIN

    FOR detail IN DETAIL_LIST LOOP
    
        ATET_SAVINGS_BANK_PKG.CREATE_ACCOUNT(detail.PERSON_ID, 'SAVINGS_ELEMENT_NAME', 'SAV_CODE_COMB');
       
    
        IF ATET_SAVINGS_BANK_PKG.GET_MEMBER_IS_SAVER(ATET_SAVINGS_BANK_PKG.GET_MEMBER_ID(detail.PERSON_ID)) = 'Y' THEN
            ATET_SAVINGS_BANK_PKG.CREATE_ACCOUNT(detail.PERSON_ID, 'LOAN_ELEMENT_NAME', 'LOAN_SAV_CODE_COMB');
        ELSE
            ATET_SAVINGS_BANK_PKG.CREATE_ACCOUNT(detail.PERSON_ID, 'LOAN_ELEMENT_NAME', 'LOAN_NO_SAV_CODE_COMB');
        END IF;
    
    END LOOP;

END;