SELECT ASM.EMPLOYEE_FULL_NAME,
       ASM.IS_BORROWER
  FROM ATET_SB_ENDORSEMENTS ASE,
       ATET_SB_MEMBERS      ASM
 WHERE ASE.LOAN_ID = :P_LOAN_ID
   AND ASE.MEMBER_BORROWER_ID = ASM.MEMBER_ID;
   
   
MERGE INTO ATET_SB_MEMBERS      ASM
     USING ATET_SB_ENDORSEMENTS ASE
        ON (    ASE.LOAN_ID = :P_LOAN_ID
            AND ASE.MEMBER_BORROWER_ID = ASM.MEMBER_ID)
WHEN MATCHED THEN 
UPDATE SET ASM.IS_BORROWER = 'N';

ROLLBACK;