SELECT ABREVIATE_PERIOD_TYPE,
        PERIOD_TYPE,
        PAYROLL_ID,
        PAYROLL_NAME,
        MEMBER_ID,
        PERSON_ID,
        EMPLOYEE_NUMBER,
        EMPLOYEE_FULL_NAME,
        PERSON_TYPE,
        IS_SAVER,
        TRANSACTION_CODE,
        EARNED_DATE,
        DEBIT_AMOUNT,
        CREDIT_AMOUNT,
        ACCOUNTED_FLAG,
        REQUEST_ID
  FROM ATET_LOANS_TRANSACTIONS_TB
 WHERE 1 = 1
   AND REQUEST_ID = :CP_REQUEST_ID
                