SELECT 
    CONSOLIDATION_SET_NAME
FROM PAY_CONSOLIDATION_SETS CONSOLIDATION,
     PAY_ALL_PAYROLLS_F PAYROLL
WHERE PAYROLL.CONSOLIDATION_SET_ID = CONSOLIDATION.CONSOLIDATION_SET_ID
  AND PAYROLL.PAYROLL_ID = :P_PAYROLL_ID