SELECT UPPER(HOU.NAME)          COMPANY_NAME,
       UPPER(HL.ADDRESS_LINE_1) LOCATION_1,
       ('COL. '  || UPPER(HL.ADDRESS_LINE_2) || 
        ' C.P. ' || UPPER(HL.POSTAL_CODE) ||
        ' '      || UPPER(HL.TOWN_OR_CITY) ||
        ', '     || UPPER(HL.REGION_1)   || '.')  AS  LOCATION_2,
       ('TEL. ' || TO_CHAR(REGEXP_REPLACE(HL.TELEPHONE_NUMBER_1,'\(|\)| |-',''), '00g000g000g0000', 'nls_numeric_characters=.-') ||
        ' RFC. '|| SUBSTR(HOI.ORG_INFORMATION2, 0, 3) || 
        '-'     || SUBSTR(HOI.ORG_INFORMATION2, 4, 6) ||
        '-'     || SUBSTR(HOI.ORG_INFORMATION2, 10, 3) )AS  LOCATION_3
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_LOCATIONS                 HL,
       HR_ORGANIZATION_INFORMATION  HOI
 WHERE 1 = 1
   AND HOU.ORGANIZATION_ID = :P_ORG_ID
   AND HOU.LOCATION_ID = HL.LOCATION_ID
   AND HOI.ORGANIZATION_ID = HOU.ORGANIZATION_ID
   AND HOI.ORG_INFORMATION_CONTEXT = 'MX_TAX_REGISTRATION';
   

