SELECT DISTINCT
       POPM.ORG_PAYMENT_METHOD_ID,
       POPM.PAYMENT_TYPE_ID,
       POPM.ORG_PAYMENT_METHOD_NAME,
       PPT.PAYMENT_TYPE_NAME
  FROM PAY_ORG_PAYMENT_METHODS_F    POPM,
       PAY_PAYMENT_TYPES_TL         PPT
 WHERE 1 = 1
   AND POPM.PAYMENT_TYPE_ID = PPT.PAYMENT_TYPE_ID
   AND (   PPT.PAYMENT_TYPE_NAME LIKE 'Direct Deposit'
        OR PPT.PAYMENT_TYPE_NAME LIKE 'Depósito Directo')
   AND PPT.LANGUAGE = USERENV('LANG')
   AND POPM.ORG_PAYMENT_METHOD_NAME NOT LIKE '%DESPENSA'
   AND POPM.ORG_PAYMENT_METHOD_NAME NOT LIKE '%PENSIONES'
   AND POPM.ORG_PAYMENT_METHOD_NAME LIKE '%02%';


