SELECT PPF.PERSON_ID,
       PPF.EMPLOYEE_NUMBER,
       PPF.EFFECTIVE_START_DATE,
       PPTU.EFFECTIVE_START_DATE,
       PPS.DATE_START,
       PPF.EFFECTIVE_END_DATE,
       PPTU.EFFECTIVE_END_DATE,
       PPS.ACTUAL_TERMINATION_DATE
FROM PER_PEOPLE_F               PPF,
     PER_PERSON_TYPE_USAGES_F   PPTU,
     PER_PERIODS_OF_SERVICE     PPS
WHERE PPF.PERSON_ID = 3424
  AND PPF.PERSON_ID = PPTU.PERSON_ID
  AND PPF.PERSON_ID = PPS.PERSON_ID
  AND (PPF.EFFECTIVE_START_DATE = PPTU.EFFECTIVE_START_DATE
   AND PPF.EFFECTIVE_START_DATE = PPS.DATE_START)