SELECT  decode(empresa,:p_empresa,empresa,'TODAS' ) compañia2,
        DECODE(periodo,:p_periodo,periodo,'TODOS' )  PERIODO2,
        decode(nomina,:p_nomina, nomina,'TODAS' ) NOMINA2,
        decode(estatus,:p_estatus, estatus,'CATALOGOS DE EMPLEADOS REGISTRADOS Y CANCELADOS') ESTATUS2,
        decode(ano,:p_ano, ano,'TODOS') ano2,
        empresa, 
        nomina,
        periodo, 
        id_empleado, 
        nombre_completo,
        apellido_paterno, 
        apellido_materno, 
        nombres, 
        segundo_nombre, 
        calle,
        num_ext, 
        num_int, 
        colonia, 
        delegacion_o_municipio,
        localidad_o_poblacion, 
        estado, 
        pais, 
        codigo_postal, 
        telefono, 
        sexo,
        nationalidad, 
        lug_nacimiento, 
        fecha_nac, 
        nivel_de_estudios, 
        t_contrato,
        terminacion, 
        num_gerencia, 
        gerencia, 
        num_departamento,
        departamento,
        puesto, 
        trabajo, 
        turno, 
        sind,
        rfc, 
        curp, 
        nss,
        delegacion_imss, 
        sub_delegaciÓn_imss, 
        uni_med_fam, 
        reg_patronal,
        fecha_alta_cia, 
        fecha_alta_imss, 
        sueldo_base, 
        s_d_i, 
        seguro, 
        bono_despensa,  
        unic_ingreso,
        forma_pago_despensa, 
        cta_bono_desp, 
        num_tarjeta_despensa,
        tipo_pago_sdo,  
        banco_deposito, 
        cuenta_bancaria, 
        banko,
        afore,
        credito_infonavit,
        fecha_credito, 
        tipoc, 
        valor_descuento, 
        saldo_inicial, 
        saldo_actual,
        porcentaje "% PENSIÓN ALIMENTICIA",
        monto "IMPORTE PENSIÓN ALIMENTICIA",     
        correo_e, 
        estado_civil, 
        regimen_matrimonial,
        estatus,
        fecha_baja, 
        area
  FROM pac_employee_v
  WHERE 1=1
     AND empresa = NVL (:p_empresa,empresa)
     AND periodo = NVL (:p_periodo, periodo)
     AND nomina = NVL (:p_nomina, nomina)
     AND estatus = NVL (:p_estatus, estatus)
     AND ano = NVL (:p_ano, ano)