UPDATE PAC_VISITS_CONTROL_TB
   SET CHECK_IN = NULL,
       CHECK_OUT = NULL,
       VISITOR_LENGTH_STAY = NULL
 WHERE VISITOR_DAY_ID = '150916001';
 
 COMMIT;
 
 
 SELECT TO_CHAR(TO_DATE(:DATETIME, 'DD-MM-YYYY HH24:MI:SS'), 'HH24:MI:SS') 
   FROM DUAL;
   
   

SELECT FLOOR(((TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_OUT, 'DD-MM-YYYY HH24:MI:SS')-TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_IN, 'DD-MM-YYYY HH24:MI:SS'))*24*60*60)/3600)
       || ' HR ' ||
       FLOOR((((TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_OUT, 'DD-MM-YYYY HH24:MI:SS')-TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_IN, 'DD-MM-YYYY HH24:MI:SS'))*24*60*60) -
       FLOOR(((TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_OUT, 'DD-MM-YYYY HH24:MI:SS')-TO_DATE(TO_CHAR(SYSDATE, 'DD-MM-YYYY') || ' ' || PVC.CHECK_IN, 'DD-MM-YYYY HH24:MI:SS'))*24*60*60)/3600)*3600)/60)
       || ' MIN' 
  FROM PAC_VISITS_CONTROL_TB PVC
 WHERE 1 = 1
   AND PVC.VISITOR_DAY_ID = '150916001';   
   