SELECT TO_CHAR(SYSDATE, 'YYMMDD') ||
       TRIM(TO_CHAR((COUNT(PVC.VISITOR_DAY_ID) + 1), '000'))
  FROM PAC_VISITS_CONTROL_TB PVC
 WHERE 1 = 1
   AND PVC.VISITOR_DAY_ID LIKE (TO_CHAR(SYSDATE, 'YYMMDD') ||'%');