SELECT TRIM(SUBSTR(HOU.NAME, INSTR(HOU.NAME, ' '))) "DEPARTMENT",
       PPF.EMPLOYEE_NUMBER,
       PPF.FULL_NAME                                "FULL_NAME"
  FROM PER_PEOPLE_F             PPF,
       PER_PERSON_TYPES         PPT,
       PER_ASSIGNMENTS_F        PAF,
       PAY_PAYROLLS_F           PPAF,
       HR_ORGANIZATION_UNITS    HOU,
       HR_LOOKUPS               HLU,
       HR_LOCATIONS             HL
 WHERE 1 = 1
   AND PPF.PERSON_TYPE_ID = PPT.PERSON_TYPE_ID
   AND PPF.PERSON_ID = PAF.PERSON_ID
   AND PPAF.PAYROLL_ID = PAF.PAYROLL_ID
   AND PAF.ORGANIZATION_ID = HOU.ORGANIZATION_ID
   AND PPT.USER_PERSON_TYPE IN ('Employee', 'Empleado')
   AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
   AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
   AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
   AND HOU.TYPE = HLU.LOOKUP_CODE
   AND HLU.LOOKUP_TYPE = 'ORG_TYPE'
   AND HLU.MEANING = 'DEPARTAMENTO'
   AND HOU.LOCATION_ID = HL.LOCATION_ID
   AND HL.LOCATION_CODE = 'DIR_TEH'
   AND PPAF.PAYROLL_NAME IN ('02_QUIN - INMOBILIARIA', 
                             '02_QUIN - EJEC CONFIANZA', 
                             '02_QUIN - CONFIDENCIAL')
 ORDER BY   DEPARTMENT,
            FULL_NAME
   