SELECT PPF.PERSON_ID,
       PPF.EMPLOYEE_NUMBER,
       PPF.FULL_NAME,
       TRIM(SUBSTR(HOU.NAME, INSTR(HOU.NAME, ' '))) AS DEPTO
  FROM PER_PEOPLE_F             PPF,
       PER_PERSON_TYPES         PPT,
       PER_ASSIGNMENTS_F        PAF,
       HR_ORGANIZATION_UNITS    HOU,
       HR_LOOKUPS               HLU,
       HR_LOCATIONS             HL
 WHERE 1 = 1
   AND PPF.PERSON_TYPE_ID = PPT.PERSON_TYPE_ID
   AND PPF.PERSON_ID = PAF.PERSON_ID
   AND PAF.ORGANIZATION_ID = HOU.ORGANIZATION_ID
   AND PPT.USER_PERSON_TYPE IN ('Employee', 'Empleado')
   AND PPF.CURRENT_EMPLOYEE_FLAG = 'Y'
   AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE AND PPF.EFFECTIVE_END_DATE
   AND SYSDATE BETWEEN PAF.EFFECTIVE_START_DATE AND PAF.EFFECTIVE_END_DATE
   AND HOU.TYPE = HLU.LOOKUP_CODE
   AND HLU.LOOKUP_TYPE = 'ORG_TYPE'
   AND HLU.MEANING = 'DEPARTAMENTO'
   AND HOU.LOCATION_ID = HL.LOCATION_ID
   AND HL.LOCATION_CODE = 'DIR_TEH'
 ORDER BY PPF.FULL_NAME