SELECT DISTINCT
       PVC.VISITOR_NAME
  FROM PAC_VISITS_CONTROL_TB    PVC
 WHERE 1 = 1;
 
 
SELECT DISTINCT
       PVC.VISITOR_COMPANY
  FROM PAC_VISITS_CONTROL_TB    PVC
 WHERE 1 = 1;
 
 
SELECT DISTINCT
       PVC.OTHER_IDENTIFICATION_NAME
  FROM PAC_VISITS_CONTROL_TB    PVC
 WHERE 1 = 1;