SELECT HOU.ORGANIZATION_ID,
       HOU.NAME,
       HLU.MEANING
  FROM HR_ORGANIZATION_UNITS        HOU,
       HR_LOOKUPS                   HLU,
       HR_LOCATIONS                 HL                 
 WHERE 1 = 1
   AND HOU.TYPE = HLU.LOOKUP_CODE
   AND HLU.LOOKUP_TYPE = 'ORG_TYPE'
   AND HLU.MEANING = 'DEPARTAMENTO'
   AND HOU.LOCATION_ID = HL.LOCATION_ID
   AND HL.LOCATION_CODE = 'DIR_TEH'
   