SELECT *
  FROM ALL_OBJECTS
 WHERE OBJECT_TYPE LIKE '%JAVA%'
--   AND STATUS = 'INVALID'
--   AND TO_DATE(CREATED, 'DD/MM/RRRR') = TO_DATE(SYSDATE, 'DD/MM/RRRR') 
 ORDER BY CREATED DESC;
 
 
CREATE OR REPLACE FUNCTION APPS.TEST_CONNECTION(
    P_DIRECTORY VARCHAR2
  )
  RETURN VARCHAR2
  AS LANGUAGE JAVA NAME 'CFDI_Verification.test_Connection(java.lang.String) return java.lang.String';
  
CREATE OR REPLACE PROCEDURE list_directories (dir IN VARCHAR2)
AS
LANGUAGE JAVA
NAME 'CFDI_Verification.list_directories(java.lang.String)';
  
  
  
DECLARE
    P_RESULT        VARCHAR2(100);
BEGIN
    SELECT APPS.TEST_CONNECTION('Calvario_Servicios')
    INTO P_RESULT
    FROM DUAL;
    
    DBMS_OUTPUT.PUT_LINE(P_RESULT);
END;


BEGIN
    SET SERVEROUTPUT ON;

END;