DECLARE
    RESULT  VARCHAR2(100);
BEGIN

    SELECT PAC_CFDI_FUNCTIONS_PKG.CFDI_VERIFICATION_TEST('Calvario_Servicios')
    INTO RESULT
    FROM DUAL;
    
    DBMS_OUTPUT.PUT_LINE(RESULT);
    
END;



SELECT *
  FROM ALL_OBJECTS
 WHERE OBJECT_TYPE LIKE '%JAVA%'
 ORDER BY CREATED DESC;