-- ALTER SESSION SET NLS_LANGUAGE = 'LATIN AMERICAN SPANISH';
-- ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';

SELECT *
  FROM PAC_EMPLOYEE_ACT_V   PEA
 WHERE 1 = 1 
   AND PEA.EMPRESA = 'El CALVARIO SERVICIOS SA DE CV'
   AND PEA.PERIODO  = 'QUINCENAL'
   AND PEA.NOMINA = '02_QUIN - EJEC CONFIANZA'
   AND PEA.ESTATUS = 'EMPLEADO'
   AND PEA.ANO = '2015';
   
   
SELECT *
  FROM PAC_ESTATUS_EMP_V;