LOAD DATA
APPEND INTO TABLE APPS.XXCALV_INV_FISICO_TB
Fields terminated by "," Optionally enclosed by '"'
(
  BARCODE,
  INVENTORY_ITEM_ID NULLIF (INVENTORY_ITEM_ID="NULL"),
  ITEM_TYPE,
  ITEM_DESC,
  CAJAS NULLIF (CAJAS="NULL"),
  SCAN_DATE DATE "MM/DD/YYYY" NULLIF (SCAN_DATE="NULL")
)
