SELECT *
  FROM XXCALV_REND_X_DESTINO;


SELECT *
  FROM XXCALV_REND_X_DESTINO
 WHERE 1 = 1
   AND DESTINO IS NOT NULL;  
   
UPDATE XXCALV_REND_X_DESTINO
   SET AREA = 'REPARTO'
 WHERE 1 = 1
   AND DESTINO IS NOT NULL;
   
SELECT *
  FROM XXCALV_REND_X_DESTINO
 WHERE 1 = 1
   AND DESTINO IS NULL;
   
   
UPDATE XXCALV_REND_X_DESTINO
   SET AREA = 'OTRO'
 WHERE 1 = 1
   AND DESTINO IS NULL;
   
   
   COMMIT;
  
