SELECT 
       PFED.DEPARTURE_DATE,
       PFET1.VEHICLE_ID,
       PFET1.VEHICLE              AS    VEHICLE_TRAILER,
       PFET2.VEHICLE              AS    VEHICLE_TOWING,
       PFED.DRIVER_NAME,
       PFET2.ATTRIBUTE1           AS    DESTINATION_NAME,
       PFEC.ATTRIBUTE1            AS    CUSTOMER_NAME,
       PFEC.ORDER_NUMBER,
       PFET2.ATTRIBUTE2           AS    BOX_NUMBER,
       PFEC.STAMP1,
       PFEC.STAMP2,
       PFEC.STAMP3
  FROM PAC_FUEL_EC_DEPARTURES     PFED,
       PAC_FUEL_EC_DETAILS        PFET1,
       PAC_FUEL_EC_DETAILS        PFET2,
       PAC_FUEL_EC_CERTIFICATES   PFEC
 WHERE 1 = 1
   AND PFED.DEPARTURE_TYPE = 'SALIDA'
   AND PFET1.DEPARTURE_ID = PFED.DEPARTURE_ID
   AND PFET1.VEHICLE_TYPE IN ('TRACTOCAMION', 'TORTON')
   AND PFET2.DEPARTURE_ID = PFED.DEPARTURE_ID
   AND PFET2.VEHICLE_TYPE IN ('REMOLQUE', 'SEMIREMOLQUE')
   AND PFEC.DEPARTURE_ID = PFED.DEPARTURE_ID
   AND PFEC.DETAIL_ID = PFET2.DETAIL_ID
   AND PFED.DEPARTURE_DATE BETWEEN :CP_START_DATE AND :CP_END_DATE
   AND PFET1.VEHICLE_ID = NVL(:P_VEHICLE_ID, PFET1.VEHICLE_ID)
   AND PFED.DRIVER_NAME = NVL(:P_DRIVER_NAME, PFED.DRIVER_NAME)
   AND PFED.TO_ORG_NAME = NVL(:P_DESTINATION_NAME, PFED.TO_ORG_NAME)
   AND PFEC.ATTRIBUTE1  = NVL(:P_CUSTOMER_NAME, PFEC.ATTRIBUTE1)
 ORDER BY PFED.DEPARTURE_DATE,
          PFET1.VEHICLE,
          PFET2.VEHICLE;

