SELECT F.CLAVE_COMPANIA,
       F.NOMBRE_COMPANIA,
       H.CLAVE_GERENCIA,
       H.NOMBRE_GERENCIA,
       H.CLAVE_AREA,
       H.NOMBRE_AREA,
       D.CLAVE_DEPARTAMENTO,
       D.NOMBRE_DEPARTAMENTO,
       D.CLAVE_CENTRO_COSTOS,
       D.NOMBRE_CENTRO_COSTOS,
       D.CLAVE_PUESTO,
       D.NOMBRE_PUESTO,
       D.CUADRO_BASICO_AUTORIZADO,
       COUNT(DISTINCT PAF1.PERSON_ID)                   AS  "CUADRO_BASICO_OCUPADO",
       COUNT(DISTINCT PAF2.PERSON_ID)                   AS  "EVENTUALES"
  FROM (SELECT FFV.FLEX_VALUE           AS  CLAVE_DEPARTAMENTO,
               FFVT.DESCRIPTION         AS  NOMBRE_DEPARTAMENTO,
               FFV_CC.FLEX_VALUE        AS  CLAVE_CENTRO_COSTOS,
               FFVT_CC.DESCRIPTION      AS  NOMBRE_CENTRO_COSTOS,
               PPD.SEGMENT3             AS  CLAVE_PUESTO,
               PPD.SEGMENT2             AS  DEPARTAMENTO,
               PPD.SEGMENT1             AS  NOMBRE_PUESTO,
               HAPF.FTE                 AS  CUADRO_BASICO_AUTORIZADO,
               HAPF.POSITION_ID
          FROM PER_POSITION_DEFINITIONS     PPD,
               HR_ALL_POSITIONS_F           HAPF,
               HR_ORGANIZATION_UNITS        HOU,
               FND_FLEX_VALUE_SETS          FFVS,
               FND_FLEX_VALUES              FFV,
               FND_FLEX_VALUES_TL           FFVT,
               FND_FLEX_VALUE_SETS          FFVS_CC,
               FND_FLEX_VALUES              FFV_CC,
               FND_FLEX_VALUES_TL           FFVT_CC
         WHERE 1 = 1
           AND PPD.POSITION_DEFINITION_ID = HAPF.POSITION_DEFINITION_ID
           AND SYSDATE BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE
           AND HOU.ORGANIZATION_ID = HAPF.ORGANIZATION_ID
           AND FFVS.FLEX_VALUE_SET_NAME = 'XXCALV_DEPA'
           AND FFV.FLEX_VALUE_SET_ID = FFVS.FLEX_VALUE_SET_ID
           AND FFVT.LANGUAGE = USERENV('LANG')
           AND FFV.FLEX_VALUE_ID = FFVT.FLEX_VALUE_ID
           AND FFV.ENABLED_FLAG = 'Y'
           AND FFV.FLEX_VALUE = PPD.SEGMENT2 
           AND FFVS_CC.FLEX_VALUE_SET_NAME = 'CC_ CALVARIO'
           AND FFV_CC.FLEX_VALUE_SET_ID = FFVS_CC.FLEX_VALUE_SET_ID
           AND FFVT_CC.LANGUAGE = USERENV('LANG')
           AND FFV_CC.FLEX_VALUE_ID = FFVT_CC.FLEX_VALUE_ID
           AND FFV_CC.ENABLED_FLAG = 'Y'
           AND FFV_CC.FLEX_VALUE = HOU.ATTRIBUTE7
       ) D
  LEFT JOIN PER_ALL_ASSIGNMENTS_F   PAF1 
         ON (    D.POSITION_ID = PAF1.POSITION_ID 
             AND PAF1.EMPLOYMENT_CATEGORY LIKE '%MX1_P%'
             AND (    PAF1.EFFECTIVE_START_DATE <= SYSDATE
                  AND PAF1.EFFECTIVE_END_DATE >= LAST_DAY(SYSDATE))
             AND PAF1.ASSIGNMENT_STATUS_TYPE_ID = 1)
  LEFT JOIN PER_ALL_ASSIGNMENTS_F   PAF2
         ON (    D.POSITION_ID = PAF2.POSITION_ID 
             AND PAF2.EMPLOYMENT_CATEGORY LIKE '%MX2_E%'
             AND (    PAF2.EFFECTIVE_START_DATE <= SYSDATE
                  AND PAF2.EFFECTIVE_END_DATE >= LAST_DAY(SYSDATE))
             AND PAF2.ASSIGNMENT_STATUS_TYPE_ID = 1)
  LEFT JOIN (SELECT PPG.PEOPLE_GROUP_ID,
                    PPG.SEGMENT1             AS  CLAVE_AREA,
                    FFVT_A.DESCRIPTION         AS  NOMBRE_AREA,
                    FFV.FLEX_VALUE           AS  CLAVE_GERENCIA,
                    FFVT.DESCRIPTION         AS  NOMBRE_GERENCIA
               FROM PAY_PEOPLE_GROUPS        PPG,
                    FND_FLEX_VALUE_SETS      FFVS,
                    FND_FLEX_VALUES          FFV,
                    FND_FLEX_VALUES_TL       FFVT,
                    FND_FLEX_VALUE_SETS      FFVS_A,
                    FND_FLEX_VALUES          FFV_A,
                    FND_FLEX_VALUES_TL       FFVT_A
              WHERE 1 = 1 
                AND FFVS.FLEX_VALUE_SET_NAME = 'CALV_GERENCIAS'
                AND FFVS.FLEX_VALUE_SET_ID = FFV.FLEX_VALUE_SET_ID
                AND FFV.FLEX_VALUE_ID = FFVT.FLEX_VALUE_ID
                AND FFVT.LANGUAGE = USERENV('LANG')
                AND PPG.SEGMENT2 = FFV.FLEX_VALUE
                AND FFVS_A.FLEX_VALUE_SET_NAME = 'CALV_AREA'
                AND FFVS_A.FLEX_VALUE_SET_ID = FFV_A.FLEX_VALUE_SET_ID
                AND FFV_A.FLEX_VALUE_ID = FFVT_A.FLEX_VALUE_ID
                AND FFVT_A.LANGUAGE = USERENV('LANG')
                AND PPG.SEGMENT1 = FFV_A.FLEX_VALUE)       H
             ON H.PEOPLE_GROUP_ID = NVL(PAF1.PEOPLE_GROUP_ID, PAF2.PEOPLE_GROUP_ID)
  LEFT JOIN (SELECT FLV1.LOOKUP_CODE    CLAVE_COMPANIA,
                    FLV1.MEANING        NOMBRE_COMPANIA,
                    PPF.PAYROLL_ID
               FROM PAY_PAYROLLS_F           PPF,
                    FND_LOOKUP_VALUES        FLV1
              WHERE 1 = 1
                AND FLV1.LOOKUP_TYPE = 'NOMINAS POR EMPLEADOR LEGAL'
                AND FLV1.LOOKUP_CODE = SUBSTR(PPF.PAYROLL_NAME,0,2)
                AND FLV1.LANGUAGE = USERENV('LANG'))          F
         ON (F.PAYROLL_ID = NVL(PAF1.PAYROLL_ID, PAF2.PAYROLL_ID))
 WHERE 1 = 1
 GROUP 
    BY F.CLAVE_COMPANIA,
       F.NOMBRE_COMPANIA,
       H.CLAVE_GERENCIA,
       H.NOMBRE_GERENCIA,
       H.CLAVE_AREA,
       H.NOMBRE_AREA,
       D.CLAVE_DEPARTAMENTO,
       D.NOMBRE_DEPARTAMENTO,
       D.CLAVE_CENTRO_COSTOS,
       D.NOMBRE_CENTRO_COSTOS,
       D.CLAVE_PUESTO,
       D.NOMBRE_PUESTO,
       D.CUADRO_BASICO_AUTORIZADO
 ORDER
    BY F.CLAVE_COMPANIA,
       H.CLAVE_GERENCIA,
       H.CLAVE_AREA,
       D.CLAVE_DEPARTAMENTO,
       D.CLAVE_PUESTO;